project:
  type: book
  output-dir: docs

book:
  title: "A Progressive Introduction to Linear Models"
  author: "Joshua P. French"
  date: today
  chapters:
    - index.qmd
    - r-foundations.qmd
    - data-exploration.qmd
  appendices:
    - matrix-facts.qmd
    - probability-basics.qmd
    - random-variables.qmd
    - multivariate-distributions.qmd
    - random-vectors.qmd
    - estimation-inference-review.qmd
    - references.qmd

bibliography: [book.bib, packages.bib]

format:
  html:
    theme: cosmo
    css: styles.css
  pdf:
    documentclass: scrreprt



