<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>2&nbsp; Data Cleaning and Exploration – A Progressive Introduction to Linear Models</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./parameter-estimation-and-model-fitting.html" rel="next">
<link href="./r-foundations.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<link href="site_libs/htmltools-fill-0.5.8.1/fill.css" rel="stylesheet">

<script src="site_libs/htmlwidgets-1.6.4/htmlwidgets.js"></script>

<script src="site_libs/plotly-binding-4.10.4/plotly.js"></script>

<script src="site_libs/typedarray-0.1/typedarray.min.js"></script>

<script src="site_libs/jquery-3.5.1/jquery.min.js"></script>

<link href="site_libs/crosstalk-1.2.1/css/crosstalk.min.css" rel="stylesheet">

<script src="site_libs/crosstalk-1.2.1/js/crosstalk.min.js"></script>

<link href="site_libs/plotly-htmlwidgets-css-2.11.1/plotly-htmlwidgets.css" rel="stylesheet">

<script src="site_libs/plotly-main-2.11.1/plotly-latest.min.js"></script>


  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./data-exploration.html"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Cleaning and Exploration</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">A Progressive Introduction to Linear Models</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preliminaries</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./r-foundations.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R Foundations</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-exploration.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Cleaning and Exploration</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parameter-estimation-and-model-fitting.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Parameter Estimation and Model Fitting</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./interpretation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Interpreting a Fitted Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./basic-theoretical-results.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Basic theoretical results</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./matrix-facts.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Overview of matrix definitions, properties, operations, etc.</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./probability-basics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Probability Basics</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./random-variables.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">Random Variables</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./multivariate-distributions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Multivariate distributions</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./random-vectors.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">E</span>&nbsp; <span class="chapter-title">Random vectors</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./estimation-inference-review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">F</span>&nbsp; <span class="chapter-title">Review of Estimation, Hypothesis Testing, and Confidence Intervals</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#raw-palmer-penguins-data" id="toc-raw-palmer-penguins-data" class="nav-link active" data-scroll-target="#raw-palmer-penguins-data"><span class="header-section-number">2.1</span> Raw Palmer penguins data –&gt;</a></li>
  <li><a href="#initial-data-cleaning" id="toc-initial-data-cleaning" class="nav-link" data-scroll-target="#initial-data-cleaning"><span class="header-section-number">2.2</span> Initial data cleaning</a></li>
  <li><a href="#numerical-summarization-of-data" id="toc-numerical-summarization-of-data" class="nav-link" data-scroll-target="#numerical-summarization-of-data"><span class="header-section-number">2.3</span> Numerical summarization of data</a>
  <ul class="collapse">
  <li><a href="#numeric-data" id="toc-numeric-data" class="nav-link" data-scroll-target="#numeric-data"><span class="header-section-number">2.3.1</span> Numeric data</a></li>
  <li><a href="#categorical-data" id="toc-categorical-data" class="nav-link" data-scroll-target="#categorical-data"><span class="header-section-number">2.3.2</span> Categorical data</a></li>
  <li><a href="#the-summary-function" id="toc-the-summary-function" class="nav-link" data-scroll-target="#the-summary-function"><span class="header-section-number">2.3.3</span> The <code>summary</code> function</a></li>
  </ul></li>
  <li><a href="#visual-summaries-of-data" id="toc-visual-summaries-of-data" class="nav-link" data-scroll-target="#visual-summaries-of-data"><span class="header-section-number">2.4</span> Visual summaries of data</a>
  <ul class="collapse">
  <li><a href="#the-ggplot-recipe" id="toc-the-ggplot-recipe" class="nav-link" data-scroll-target="#the-ggplot-recipe"><span class="header-section-number">2.4.1</span> The ggplot recipe</a></li>
  <li><a href="#univariate-plots" id="toc-univariate-plots" class="nav-link" data-scroll-target="#univariate-plots"><span class="header-section-number">2.4.2</span> Univariate plots</a></li>
  <li><a href="#bivariate-plots" id="toc-bivariate-plots" class="nav-link" data-scroll-target="#bivariate-plots"><span class="header-section-number">2.4.3</span> Bivariate plots</a></li>
  <li><a href="#multivariate-plots" id="toc-multivariate-plots" class="nav-link" data-scroll-target="#multivariate-plots"><span class="header-section-number">2.4.4</span> Multivariate plots</a></li>
  </ul></li>
  <li><a href="#a-plan-for-data-cleaning-and-exploration" id="toc-a-plan-for-data-cleaning-and-exploration" class="nav-link" data-scroll-target="#a-plan-for-data-cleaning-and-exploration"><span class="header-section-number">2.5</span> A plan for data cleaning and exploration</a></li>
  <li><a href="#final-notes-on-missing-or-erroneous-data" id="toc-final-notes-on-missing-or-erroneous-data" class="nav-link" data-scroll-target="#final-notes-on-missing-or-erroneous-data"><span class="header-section-number">2.6</span> Final notes on missing or erroneous data</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-ch-eda" class="quarto-section-identifier"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data Cleaning and Exploration</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<hr>
<p><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/80x15.png"></a> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.</p>
<hr>
<p>A condensed, interactive version of this content is available as a Colab notebook, which can be accessed by clicking or scanning the QR code below.</p>
<p><a href="https://colab.research.google.com/github/jfrench/LinearRegression/blob/master/notebooks/02-data-exploration-notebook.ipynb"> <img src="https://raw.githubusercontent.com/jfrench/LinearRegression/c2d3c6c541f4519883c2ece5a983b836b6375bce/images/qr-data-exploration.svg" width="100"> </a></p>
<hr>
<p>We should explore every data set numerically and visually prior to modeling it. The data exploration process will help us find errors in our data, locate missing values, identify outliers and unusual observations, find patterns in our data, decide on a modeling approach, etc.</p>
<p>When we receive a data set for the first time, we often need to “prepare” it for analysis. More specifically, we may need to restructure the data so that each row is an observation and each column is a variable, convert variables to an appropriate type, improve the names of the variables, etc. The process of preparing the data into a friendly format is known as “cleaning”.</p>
<p>A systematic exploration of the data is essential to performing a correct analysis. We will demonstrate a systematic (but not exhaustive) exploration of the <code>penguins_raw</code> data set from the <strong>palmerpenguins</strong> package <span class="citation" data-cites="R-palmerpenguins">(<a href="references.html#ref-R-palmerpenguins" role="doc-biblioref">Horst, Hill, and Gorman 2022</a>)</span>.</p>
<section id="raw-palmer-penguins-data" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="raw-palmer-penguins-data"><span class="header-section-number">2.1</span> Raw Palmer penguins data –&gt;</h2>
<p>To attach a data set from an R package into our working environment, we run the <code>data</code> function while specifying the <code>name</code> of the data set to be loaded and the package that contains the data. We do this for the <code>penguins_raw</code> data below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(penguins, <span class="at">package =</span> <span class="st">"palmerpenguins"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This command actually loads two data sets: <code>penguins_raw</code>, the data set we will be looking at, and <code>penguins</code>, a simplified version of <code>penguins_raw</code>. Note that this particular data set loads in a nonstandard way; we would normally load the <code>penguins_raw</code> data using <code>data(penguins_raw, package = "palmerpenguins")</code>.</p>
<p>We could have also loaded the data set by running the following commands in the Console.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(palmerpenguins)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(penguins)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This second approach loads and attaches everything the package includes into memory (functions, data, etc). If we are going to be using many functions or objects from a package, then the second approach is sensible. Otherwise, the first approach is more precise and is better coding practice to prevent masking (as discussed in <a href="r-foundations.html" class="quarto-xref"><span>Chapter 1</span></a>) and namespace pollution.</p>
<p>The <code>penguins_raw</code> data set provides data related to various penguin species measured in the Palmer Archipelago (Antarctica), originally provided by <span class="citation" data-cites="GormanEtAl2014">Gorman, Williams, and Fraser (<a href="references.html#ref-GormanEtAl2014" role="doc-biblioref">2014</a>)</span>.</p>
<p>The data set includes 344 observations of 17 variables. The variables are:</p>
<ul>
<li><code>studyName</code>: the expedition from which the data were collected (<code>character</code>).</li>
<li><code>Sample Number</code>: the continuous number sequence for each sample (<code>numeric</code>).</li>
<li><code>Species</code>: the penguin’s species (<code>character</code>).</li>
<li><code>Region</code>: the region of the Palmer LTER sampling grid the sample was obtained (<code>character</code>).</li>
<li><code>Island</code>: the island on which the penguin was observed (<code>character</code>).</li>
<li><code>Stage</code>: the reproductive stage of the observation (<code>character</code>).</li>
<li><code>Individual ID</code>: the unique identification number of the observations (<code>character</code>).</li>
<li><code>Clutch Completion</code>: whether the study nest was observed with a “full clutch” of 2 eggs (<code>character</code>).</li>
<li><code>Date Egg</code>: the date that the study nest was observed with 1 egg (<code>Date</code>).</li>
<li><code>Culman Length (mm)</code>: the length of the dorsal ridge of the penguin’s bill in millimeters (<code>numeric</code>).</li>
<li><code>Culmen Depth (mm)</code>: the depth of the dorsal ridge of the penguin’s bill in millimeters (<code>numeric</code>).</li>
<li><code>Flipper Length (mm)</code>: the penguin’s flipper length in millimeters (<code>numeric</code>).</li>
<li><code>Body Mass (g)</code>: the penguin’s body mass in grams (<code>numeric</code>).</li>
<li><code>Sex</code>: the penguin’s sex (<code>character</code>).</li>
<li><code>Delta 15 N (o/oo)</code>: the ratio of stable isotopes 15N:14N (<code>numeric</code>).</li>
<li><code>Delta 13 C (o/oo)</code>: the ratio of stable isotopes 15C:12C (<code>numeric</code>).</li>
<li><code>Comments</code>: additional information about the observation (<code>character</code>).</li>
</ul>
</section>
<section id="initial-data-cleaning" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="initial-data-cleaning"><span class="header-section-number">2.2</span> Initial data cleaning</h2>
<p>The <code>str</code> function is a great first function to apply on a newly loaded data set because it provides a general overview of the data’s structure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(penguins_raw, <span class="at">give.attr =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [344 × 17] (S3: tbl_df/tbl/data.frame)
 $ studyName          : chr [1:344] "PAL0708" "PAL0708" "PAL0708" "PAL0708" ...
 $ Sample Number      : num [1:344] 1 2 3 4 5 6 7 8 9 10 ...
 $ Species            : chr [1:344] "Adelie Penguin (Pygoscelis adeliae)" "Adelie Penguin (Pygoscelis adeliae)" "Adelie Penguin (Pygoscelis adeliae)" "Adelie Penguin (Pygoscelis adeliae)" ...
 $ Region             : chr [1:344] "Anvers" "Anvers" "Anvers" "Anvers" ...
 $ Island             : chr [1:344] "Torgersen" "Torgersen" "Torgersen" "Torgersen" ...
 $ Stage              : chr [1:344] "Adult, 1 Egg Stage" "Adult, 1 Egg Stage" "Adult, 1 Egg Stage" "Adult, 1 Egg Stage" ...
 $ Individual ID      : chr [1:344] "N1A1" "N1A2" "N2A1" "N2A2" ...
 $ Clutch Completion  : chr [1:344] "Yes" "Yes" "Yes" "Yes" ...
 $ Date Egg           : Date[1:344], format: "2007-11-11" "2007-11-11" ...
 $ Culmen Length (mm) : num [1:344] 39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ Culmen Depth (mm)  : num [1:344] 18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ Flipper Length (mm): num [1:344] 181 186 195 NA 193 190 181 195 193 190 ...
 $ Body Mass (g)      : num [1:344] 3750 3800 3250 NA 3450 ...
 $ Sex                : chr [1:344] "MALE" "FEMALE" "FEMALE" NA ...
 $ Delta 15 N (o/oo)  : num [1:344] NA 8.95 8.37 NA 8.77 ...
 $ Delta 13 C (o/oo)  : num [1:344] NA -24.7 -25.3 NA -25.3 ...
 $ Comments           : chr [1:344] "Not enough blood for isotopes." NA NA "Adult not sampled." ...</code></pre>
</div>
</div>
<p>We see that the <code>penguins_raw</code> object is a <code>tibble</code>, a special kind of data frame provided by the <strong><code>tibble</code></strong> package <span class="citation" data-cites="R-tibble">(<a href="references.html#ref-R-tibble" role="doc-biblioref">Müller and Wickham 2023</a>)</span> as part of the broader <strong><code>tidyverse</code></strong>. It has 344 rows and 17 columns. In general, a <code>tibble</code> will function like a standard data frame, though its behavior may change when <strong><code>tidyverse</code></strong> packages are loaded. In the code below, we confirm that <code>penguins_raw</code> qualifies as a <strong>base</strong> R <code>data.frame</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">is.data.frame</span>(penguins_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] TRUE</code></pre>
</div>
</div>
<p>An alternative to <code>str</code> is the <code>glimpse</code> function from the <code>dplyr</code> package. <code>dplyr::glimpse</code> also summarizes the structure of an object, but also automatically formats the printed output to the size of the Console to make it more readable. An example is provided below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>dplyr<span class="sc">::</span><span class="fu">glimpse</span>(penguins_raw)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 344
Columns: 17
$ studyName             &lt;chr&gt; "PAL0708", "PAL0708", "PAL0708", "PAL0708", "PAL…
$ `Sample Number`       &lt;dbl&gt; 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 1…
$ Species               &lt;chr&gt; "Adelie Penguin (Pygoscelis adeliae)", "Adelie P…
$ Region                &lt;chr&gt; "Anvers", "Anvers", "Anvers", "Anvers", "Anvers"…
$ Island                &lt;chr&gt; "Torgersen", "Torgersen", "Torgersen", "Torgerse…
$ Stage                 &lt;chr&gt; "Adult, 1 Egg Stage", "Adult, 1 Egg Stage", "Adu…
$ `Individual ID`       &lt;chr&gt; "N1A1", "N1A2", "N2A1", "N2A2", "N3A1", "N3A2", …
$ `Clutch Completion`   &lt;chr&gt; "Yes", "Yes", "Yes", "Yes", "Yes", "Yes", "No", …
$ `Date Egg`            &lt;date&gt; 2007-11-11, 2007-11-11, 2007-11-16, 2007-11-16,…
$ `Culmen Length (mm)`  &lt;dbl&gt; 39.1, 39.5, 40.3, NA, 36.7, 39.3, 38.9, 39.2, 34…
$ `Culmen Depth (mm)`   &lt;dbl&gt; 18.7, 17.4, 18.0, NA, 19.3, 20.6, 17.8, 19.6, 18…
$ `Flipper Length (mm)` &lt;dbl&gt; 181, 186, 195, NA, 193, 190, 181, 195, 193, 190,…
$ `Body Mass (g)`       &lt;dbl&gt; 3750, 3800, 3250, NA, 3450, 3650, 3625, 4675, 34…
$ Sex                   &lt;chr&gt; "MALE", "FEMALE", "FEMALE", NA, "FEMALE", "MALE"…
$ `Delta 15 N (o/oo)`   &lt;dbl&gt; NA, 8.94956, 8.36821, NA, 8.76651, 8.66496, 9.18…
$ `Delta 13 C (o/oo)`   &lt;dbl&gt; NA, -24.69454, -25.33302, NA, -25.32426, -25.298…
$ Comments              &lt;chr&gt; "Not enough blood for isotopes.", NA, NA, "Adult…</code></pre>
</div>
</div>
<p>Another thing that we notice about <code>penguins_raw</code> is that it has terrible variable names. The variable names have a mixture of lowercase and uppercase letters, parentheses, and even spaces! This makes it complicated to access variables in the data frame. To access the flipper length variable, we would have to use something like the command below. Note the <code>` `</code> around <code>Flipper Length (mm)</code> because of the spaces in the variable name.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">max.print =</span> <span class="dv">18</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>penguins_raw<span class="sc">$</span><span class="st">`</span><span class="at">Flipper Length (mm)</span><span class="st">`</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 181 186 195  NA 193 190 181 195 193 190 186 180 182 191 198 185 195 197
 [ reached getOption("max.print") -- omitted 326 entries ]</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">max.print =</span> <span class="dv">99999</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In <em>The tidyverse style guide</em> <span class="citation" data-cites="tidyversestyleguide">(<a href="references.html#ref-tidyversestyleguide" role="doc-biblioref">Wickham 2022</a>)</span>, Hadley Wickham recommends:</p>
<blockquote class="blockquote">
<p>Variable and function names should use only lowercase letters, numbers, and _. Use underscores (_) (so called snake case) to separate words within a name.</p>
</blockquote>
<p>We will apply this recommendation to the <code>penguins_raw</code> data below.</p>
<p>Additionally, many variables will be extraneous for our future analyses, so we will select only the ones that we will use in the future. We the <code>subset</code> function to select the <code>Species</code>, <code>Island</code>, <code>Culmen Length (mm)</code>, <code>Culmen Depth (mm)</code>, <code>Flipper Length (mm)</code>, <code>Body Mass (g)</code>, and <code>Sex</code> variables of <code>penguins_raw</code> and assign the subsetted data frame the name <code>penguins_clean</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>penguins_clean <span class="ot">&lt;-</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>  penguins_raw <span class="sc">|&gt;</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(<span class="at">select =</span> <span class="fu">c</span>(<span class="st">"Species"</span>, <span class="st">"Island"</span>, <span class="st">"Culmen Length (mm)"</span>, <span class="st">"Culmen Depth (mm)"</span>,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>                    <span class="st">"Flipper Length (mm)"</span>, <span class="st">"Body Mass (g)"</span>, <span class="st">"Sex"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>To rename the columns of <code>penguins_clean</code>, we use the <code>names</code> function to extract the variable names of the data frame and replace them with a vector containing the desired variable names. A second usage of <code>names</code> confirms that the data frame now has improved column names.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># access variable names and replace with new names</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(penguins_clean) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"species"</span>, <span class="st">"island"</span>, <span class="st">"bill_length"</span>, <span class="st">"bill_depth"</span>,</span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>                           <span class="st">"flipper_length"</span>, <span class="st">"body_mass"</span>, <span class="st">"sex"</span>)</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="co"># look at new variable names</span></span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(penguins_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "species"        "island"         "bill_length"    "bill_depth"    
[5] "flipper_length" "body_mass"      "sex"           </code></pre>
</div>
</div>
<p>There are still some issues with <code>penguins_clean</code>. Notably, the <code>species</code>, <code>island</code>, and <code>sex</code> variables are categorical but are represented as <code>character</code> vectors. These variables should each be converted to a <code>factor</code>. We use the <code>transform</code> function to convert each variable to a <code>factor</code>. Notice that we must replace the original <code>penguins_clean</code> object with the transformed object using the assignment operator. We then run the <code>str</code> function to confirm the changes.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># convert sex variable to factor, replace original object</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>penguins_clean <span class="ot">&lt;-</span></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>  penguins_clean <span class="sc">|&gt;</span></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transform</span>(<span class="at">species =</span> <span class="fu">factor</span>(species), <span class="at">island =</span> <span class="fu">factor</span>(island), <span class="at">sex =</span> <span class="fu">factor</span>(sex))</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a><span class="co"># view structure</span></span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(penguins_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   344 obs. of  7 variables:
 $ species       : Factor w/ 3 levels "Adelie Penguin (Pygoscelis adeliae)",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island        : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_length   : num  39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_depth    : num  18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_length: num  181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass     : num  3750 3800 3250 NA 3450 ...
 $ sex           : Factor w/ 2 levels "FEMALE","MALE": 2 1 1 NA 1 2 1 2 NA NA ...</code></pre>
</div>
</div>
<p>Our conversion of <code>species</code>, <code>island</code>, and <code>sex</code> to <code>factor</code> variables was successful. However, we notice that the <code>levels</code> of <code>sex</code> are <code>MALE</code> and <code>FEMALE</code>, which is visually unappealing. Also, the levels of <code>species</code> are extremely long, which can create formatting challenges. We simplify both below. First, we confirm the order of the factor levels of the two variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># determine levels of species and sex</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(penguins_clean<span class="sc">$</span>species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Adelie Penguin (Pygoscelis adeliae)"      
[2] "Chinstrap penguin (Pygoscelis antarctica)"
[3] "Gentoo penguin (Pygoscelis papua)"        </code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(penguins_clean<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "FEMALE" "MALE"  </code></pre>
</div>
</div>
<p>We now change the levels of each variable in the same order they are printed above and confirm that the changes were successful.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># update factor levels of species and sex</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(penguins_clean<span class="sc">$</span>species) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"adelie"</span>, <span class="st">"chinstrap"</span>, <span class="st">"gentoo"</span>)</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="fu">levels</span>(penguins_clean<span class="sc">$</span>sex) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"female"</span>, <span class="st">"male"</span>)</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a><span class="co"># confirm that changes took effect</span></span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(penguins_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   344 obs. of  7 variables:
 $ species       : Factor w/ 3 levels "adelie","chinstrap",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ island        : Factor w/ 3 levels "Biscoe","Dream",..: 3 3 3 3 3 3 3 3 3 3 ...
 $ bill_length   : num  39.1 39.5 40.3 NA 36.7 39.3 38.9 39.2 34.1 42 ...
 $ bill_depth    : num  18.7 17.4 18 NA 19.3 20.6 17.8 19.6 18.1 20.2 ...
 $ flipper_length: num  181 186 195 NA 193 190 181 195 193 190 ...
 $ body_mass     : num  3750 3800 3250 NA 3450 ...
 $ sex           : Factor w/ 2 levels "female","male": 2 1 1 NA 1 2 1 2 NA NA ...</code></pre>
</div>
</div>
<p>Our initial data cleaning process is now completed. As we explore our data further, it may become clear that additional data cleaning is needed.</p>
</section>
<section id="numerical-summarization-of-data" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="numerical-summarization-of-data"><span class="header-section-number">2.3</span> Numerical summarization of data</h2>
<p>Numerical exploration of a data set generally consists of computing various relevant statistics for each of the variables in a data set in order to summarize the data. The data type determines which statistics are relevant.</p>
<p><a href="#tbl-numsum" class="quarto-xref">Table&nbsp;<span>2.1</span></a> provides an overview of common numerical summaries used to explore data, the type of data that can be summarized, the characteristic summarized, and the function used to compute the statistic.</p>
<div class="cell">
<div id="tbl-numsum" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-numsum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.1: A summary of statistics frequently used to numerically summarize data, the variable type that can be summarized, the characteristic summarized, and the R function used to compute the statistic.
</figcaption>
<div aria-describedby="tbl-numsum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 37%">
<col style="width: 16%">
<col style="width: 20%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">numeric summary</th>
<th style="text-align: left;">variable type</th>
<th style="text-align: left;">summarizes</th>
<th style="text-align: left;">R function</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">mean</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">center</td>
<td style="text-align: left;"><code>mean</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">median</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">center</td>
<td style="text-align: left;"><code>median</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">variance</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">spread</td>
<td style="text-align: left;"><code>var</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">standard deviation</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">spread</td>
<td style="text-align: left;"><code>sd</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">interquartile range</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">spread</td>
<td style="text-align: left;"><code>quantile</code> (modified)</td>
</tr>
<tr class="even">
<td style="text-align: left;">quantiles</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">center and spread</td>
<td style="text-align: left;"><code>quantile</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">correlation</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">similarity</td>
<td style="text-align: left;"><code>cor</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">frequency distribution</td>
<td style="text-align: left;"><code>factor</code></td>
<td style="text-align: left;">counts</td>
<td style="text-align: left;"><code>table</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">relative frequency distribution</td>
<td style="text-align: left;"><code>factor</code></td>
<td style="text-align: left;">proportions</td>
<td style="text-align: left;"><code>table</code> (modified)</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>We provide additional explanation about the numeric summaries in what follows.</p>
<section id="numeric-data" class="level3" data-number="2.3.1">
<h3 data-number="2.3.1" class="anchored" data-anchor-id="numeric-data"><span class="header-section-number">2.3.1</span> Numeric data</h3>
<p>Numerical exploration of a set of <code>numeric</code> values usually focuses on determining the:</p>
<ol type="1">
<li>center</li>
<li>spread</li>
<li>quantiles (less common).</li>
</ol>
<p>Computing the correlation between two <code>numeric</code> variables can also be useful.</p>
<section id="measures-of-center" class="level4" data-number="2.3.1.1">
<h4 data-number="2.3.1.1" class="anchored" data-anchor-id="measures-of-center"><span class="header-section-number">2.3.1.1</span> Measures of center</h4>
<p>The sample mean and median are the most common statistics used to represent the “center” of a set of numeric values.</p>
<p>The sample mean or average is obtained by adding all values in the sample and dividing by the number of observations. The sample mean is the most commonly used measure of center. A weakness of the sample mean is that it is easily affected by outliers (values that are very large or small compared to the rest of the data values). Formally, if <span class="math inline">\(x_1, x_2, \ldots, x_n\)</span> are a sample of <span class="math inline">\(n\)</span> numeric values, then the sample mean is computed as <span class="math display">\[
\bar{x} = \frac{1}{n}\sum_{i=1}^n x_i.
\]</span> The <code>mean</code> function computes the sample mean of a set of <code>numeric</code> values.</p>
<p>The sample median is the middle value of an ordered set of values (the actual middle value when the number of values is odd and the average of the two middle values when the number of values is even). Alternatively, the median is identical to the 0.5 quantile of the data. The median is considered more “resistant” because it is not so greatly affected by outliers. The median of the values 1, 8, 7, 6, 100 is 7. The median of the values 1, 8, 7, 6, 100, 4 is 6.5. The <code>median</code> function computes the sample median of a set of a <code>numeric</code> values.</p>
<p>We compute the sample mean of the <code>body_mass</code> variable of the <code>penguins_clean</code> data in the code below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(penguins_clean<span class="sc">$</span>body_mass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] NA</code></pre>
</div>
</div>
<p>Why is the result <code>NA</code> instead of a number? In general, an <code>NA</code> value “poisons” any calculation it is part of, with the function returning <code>NA</code>. Even a single <code>NA</code> value will cause a calculation to return <code>NA</code>, even if there are thousands or millions of non-<code>NA</code> values. If you want to compute the sample mean of the non-<code>NA</code> values, then you must change the <code>na.rm</code> argument of <code>mean</code> to <code>TRUE</code>, which makes the <code>mean</code> function to temporarily remove <code>NA</code>s prior to calculation. The <code>na.rm</code> argument is provided in many other functions, as we’ll see in subsequent examples. We now compute the sample mean and median of the <code>body_mass</code> variable in <code>penguins_clean</code>, ignoring <code>NA</code> values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute sample mean and median body_mass, ignoring NAs</span></span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4201.754</code></pre>
</div>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="fu">median</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4050</code></pre>
</div>
</div>
<p>We see that the average penguin <code>body_mass</code> is approximately 4,201 grams, while the median penguin <code>body_mass</code> is 4,050 grams. Since the median is less than the mean (i.e., large values are pulling the mean in the positive direction) the data <em>may</em> be positively skewed, but we will need to look at a histogram or density plot of the data to be sure (these plots are discussed in <a href="#sec-histograms" class="quarto-xref"><span>Section 2.4.2.3</span></a> and <a href="#sec-density-plots" class="quarto-xref"><span>Section 2.4.2.4</span></a>).</p>
</section>
<section id="sec-quantiles" class="level4" data-number="2.3.1.2">
<h4 data-number="2.3.1.2" class="anchored" data-anchor-id="sec-quantiles"><span class="header-section-number">2.3.1.2</span> Quantiles</h4>
<p>Informally, the <em>p</em>th quantile (where <span class="math inline">\(0\leq p \leq 1\)</span>) of a set of values is the value that separates the smallest <span class="math inline">\(100 p\)</span>% of the values from the upper <span class="math inline">\(100(1-p)\)</span>% of the values. E.g., the 0.25 sample quantile (often called Q1) of a set of values is the value that separates the smallest 25% of the values from the largest 75% of the values. Similarly, the 0.75 sample quantile (often called Q3) of a set of values is the value that separates the smallest 75% of the values from the largest 25% of the values.</p>
<p>The <code>quantile</code> function is used to compute sample quantiles. There are many competing approaches to computing sample quantiles (which we won’t discuss or worry about). Run <code>?quantile</code> in the Console to learn more about the approaches R can use to compute sample quantiles.</p>
<p>Quantiles are useful quantifying both the center (median) and spread (minimum and maxmimum or interquartile range) of a set of values.</p>
<p>We use the <code>quantile</code> function to compute the minimum (0 quantile), Q1 (0.25 quantile), median (0.5 quantile), Q3 (0.75 quantile), and maximum (1 quantile) of <code>body_mass</code> in the code below. The desired quantiles are provided as a <code>numeric</code> vector to the <code>probs</code> argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">probs =</span> <span class="fu">c</span>(<span class="dv">0</span>, <span class="fl">0.25</span>, <span class="fl">0.5</span>, <span class="fl">0.75</span>, <span class="dv">1</span>), <span class="at">na.rm =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  0%  25%  50%  75% 100% 
2700 3550 4050 4750 6300 </code></pre>
</div>
</div>
<p>We see that the smallest and largest body masses are 2,700 grams and 6,300 grams, so the range of the data is 6,300 - 2,700 = 3,600 grams. Q1 is 3,550 grams, while Q3 is 4,750 grams. Since Q3 and the maximum are further from the median than Q1 and the minimum, respectively, this is additional evidence that this variable may be positively skewed (stretched out in the positive direction), but we must visualize the distribution of this variable to confirm this.</p>
</section>
<section id="measures-of-spread" class="level4" data-number="2.3.1.3">
<h4 data-number="2.3.1.3" class="anchored" data-anchor-id="measures-of-spread"><span class="header-section-number">2.3.1.3</span> Measures of spread</h4>
<p>In addition to identifying the center of a set of values, it is important to measure their spread, i.e., how much the values vary.</p>
<p>The sample variance and standard deviation are the most common measures of spread for numeric values. The sample variance of a set of values is the (approximate) average of the squared deviation of each observation from the sample mean. Formally, the equation for the sample variance is <span class="math display">\[
s^2 = \frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2.
\]</span> The sample standard deviation is the square root of the sample variance and is generally a more useful measure of spread because it is has the same units as the original data. The equation for the sample standard deviation is <span class="math display">\[
s = \sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i - \bar{x})^2}.
\]</span> The larger the standard deviation or variance of a set of values, the more the values vary from their sample mean. The sample standard deviation and variance can be greatly affected by outliers. The <code>var</code> function computes the sample variance while <code>sd</code> computes the sample standard deviation.</p>
<p>The interquartile range is a more resistant measure of spread based on quantiles. The interquartile range is the difference between the 0.75 and 0.25 quantiles of a data set.</p>
<p>The minimum and maximum of a set of values (in relation to their sample mean or median) can also be used to ascertain the spread of a data set. The <code>min</code> and <code>max</code> functions compute the minimum and maximum values of a set of values, respectively.</p>
<p>We compute these measures of spread for the <code>body_mass</code> variable below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">var</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># sample variance</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 643131.1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sd</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># sample standard deviation</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 801.9545</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="co"># interquartile range (names = FALSE removes text above the results)</span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">probs =</span> <span class="fl">0.75</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>, <span class="at">names =</span> <span class="cn">FALSE</span>) <span class="sc">-</span></span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">quantile</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">probs =</span> <span class="fl">0.25</span>, <span class="at">na.rm =</span> <span class="cn">TRUE</span>, <span class="at">names =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1200</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">min</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># minimum</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2700</code></pre>
</div>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">max</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">na.rm =</span> <span class="cn">TRUE</span>) <span class="co"># maximum</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 6300</code></pre>
</div>
</div>
<p>The sample variance of <code>body_mass</code> is 643,131.1 grams<sup>2</sup>, which isn’t easy to interpret. The sample standard deviation is almost 802 grams. So the “typical” deviation of a <code>body_mass</code> value from the sample mean is about 800 grams. The interquartile range is 1,200 grams. The minimum and maximum values of penguin <code>body_mass</code> match what we computed in <a href="#sec-quantiles" class="quarto-xref"><span>Section 2.3.1.2</span></a>.</p>
</section>
<section id="correlation" class="level4" data-number="2.3.1.4">
<h4 data-number="2.3.1.4" class="anchored" data-anchor-id="correlation"><span class="header-section-number">2.3.1.4</span> Correlation</h4>
<p>The correlation between two <code>numeric</code> variables quantifies the strength and direction of their linear relationship. The most common correlation statistic is Pearson’s correlation statistic. If <span class="math inline">\(x_1, x_2, x_n\)</span> and <span class="math inline">\(y_1, y_2, \ldots, y_n\)</span> are two sets of <code>numeric</code> values, then the sample correlation statistic is computed as <span class="math display">\[
r = \frac{1}{n-1}\sum_{i=1}^n\left(\frac{x_i - \bar{x}}{s_x}\right)\left(\frac{y_i - \bar{y}}{s_y}\right),
\]</span> where <span class="math inline">\(\bar{x}\)</span> and <span class="math inline">\(s_x\)</span> denote the sample mean and standard deviation of the <span class="math inline">\(x\)</span>’s while <span class="math inline">\(\bar{y}\)</span> and <span class="math inline">\(s_y\)</span> denote the sample mean and standard deviation of the <span class="math inline">\(y\)</span>’s. <span class="math inline">\(r\)</span> must be between -1 and 1. The <code>cor</code> function computes the sample correlation between two <code>numeric</code> variables.</p>
<p>The closer <span class="math inline">\(r\)</span> is to -1 or 1, the closer the data values fall to a straight line when we plot <span class="math inline">\((x_i, y_i)\)</span>, <span class="math inline">\(i=1,2,\ldots,n\)</span> in a scatter plot (discussed in <a href="#sec-scatter-plots" class="quarto-xref"><span>Section 2.4.3.1</span></a>). Sample correlation values close to 0 indicate that there is no linear relationship between the two variables. Negative <span class="math inline">\(r\)</span> values indicate a negative relationship between the two variables (as values of one variable increase, the values of the other variable tend to decrease). Positive <span class="math inline">\(r\)</span> values indicate a positive relationship between the two variables (as values of one variable increase, the values of the other variable also tend to increase).</p>
<p>In the code below, we compute the sample correlation between all <code>numeric</code> variables in <code>penguins_clean</code>. We specify <code>use = "pairwise.complete.obs"</code> so that all non-<code>NA</code> pairs of values are used in the calculation. We first determine which variables are <code>numeric</code> using the code below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="co"># determine whether each variable is numeric</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>num_col <span class="ot">&lt;-</span> <span class="fu">unlist</span>(<span class="fu">lapply</span>(penguins_clean, is.numeric))</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a><span class="co"># observe results</span></span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>num_col</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       species         island    bill_length     bill_depth flipper_length 
         FALSE          FALSE           TRUE           TRUE           TRUE 
     body_mass            sex 
          TRUE          FALSE </code></pre>
</div>
</div>
<p>We then compute the sample correlation between all pairs of <code>numeric</code> variables.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="co"># compute correlation of numeric variables</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(penguins_clean[, num_col], <span class="at">use =</span> <span class="st">"pairwise.complete.obs"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               bill_length bill_depth flipper_length  body_mass
bill_length      1.0000000 -0.2350529      0.6561813  0.5951098
bill_depth      -0.2350529  1.0000000     -0.5838512 -0.4719156
flipper_length   0.6561813 -0.5838512      1.0000000  0.8712018
body_mass        0.5951098 -0.4719156      0.8712018  1.0000000</code></pre>
</div>
</div>
<p>Commenting on the output, we see that the values of each variable are perfectly correlated with themselves (this is always true since the values in each pair are identical). The correlation between <code>bill_length</code> and <code>body_mass</code> is 0.87, so heavier penguins tend to have longer bills. Perhaps surprisingly, the correlation between <code>bill_length</code> and <code>bill_depth</code> is -0.24, so penguins with longer bills tend to have shallower (narrower) bills. Similarly, the correlation between <code>bill_depth</code> and <code>body_mass</code> is -0.47, so heavier penguins tend to have narrower bills.</p>
<p>We briefly explain why we didn’t simply use the <code>cor</code> function on <code>penguins_clean</code> directly. If we try to use <code>cor</code> on <code>penguins_clean</code> naively, then R will return an error because not all variables in <code>penguins_clean</code> are <code>numeric</code>. To account for this, we create a vector that determines whether a variable in <code>penguins_clean</code> is <code>numeric</code>. Recall that a <code>data.frame</code> object is a specially-structured <code>list</code> object, with each variable being an element of the <code>list</code>. The <code>lapply</code> function applies a function (<code>is.numeric</code> in this case) to each element of the supplied <code>list</code>. In our case, we use this to determine whether each variable is <code>numeric</code>. The result is returned as a <code>list</code>, so we use the <code>unlist</code> function to simplify the <code>list</code> to a <code>vector</code>.</p>
</section>
</section>
<section id="categorical-data" class="level3" data-number="2.3.2">
<h3 data-number="2.3.2" class="anchored" data-anchor-id="categorical-data"><span class="header-section-number">2.3.2</span> Categorical data</h3>
<p>The statistics mentioned in the previous section are generally not appropriate for a categorical variable. Instead, frequency distributions and relative frequency distributions are useful numeric summaries of categorical data.</p>
<p>A frequency distribution summarizes the number of observations having each level of a categorical variable. The <code>table</code> function produces a frequency distribution (contingency table) summarizing the number of observations for each level of a categorical variable. Note that by default, the <code>table</code> function ignores <code>NA</code> values. We provide an example below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(penguins_clean<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
female   male 
   165    168 </code></pre>
</div>
</div>
<p>We see that for the <code>sex</code> variable, there are 165 female penguins and 168 male penguins.</p>
<p>To count the <code>NA</code> values (if present), we can set the <code>useNA</code> argument of <code>table</code> to <code>"ifany"</code>, as in the example below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(penguins_clean<span class="sc">$</span>sex, <span class="at">useNA =</span> <span class="st">"ifany"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
female   male   &lt;NA&gt; 
   165    168     11 </code></pre>
</div>
</div>
<p>We see that 11 of the observations had no available information on <code>sex</code>.</p>
<p>A relative frequency distribution summarizes the proportion or percentage of observations with each level of a categorical variable. To compute the relative frequency distribution of a variable, we must divide the frequency distribution by the number of observations. If we want to ignore the <code>NA</code>s, then we can use the following code, which takes the frequency distribution of <code>sex</code> and divides by the number of non-<code>NA</code> <code>sex</code> values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># divide the frequence distribution of sex by the number of non-NA values</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(penguins_clean<span class="sc">$</span>sex)<span class="sc">/</span><span class="fu">sum</span>(<span class="sc">!</span><span class="fu">is.na</span>(penguins_clean<span class="sc">$</span>sex))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   female      male 
0.4954955 0.5045045 </code></pre>
</div>
</div>
<p>We see that slightly under 50% of the <code>sex</code> values are female (not accounting for <code>NA</code> values), while slightly more than 50% are male.</p>
<p>What is the command <code>sum(!is.na(penguins_clean$sex))</code> doing in the code above? The <code>is.na</code> function returns a <code>TRUE</code> for each value that is <code>NA</code> but otherwise returns <code>FALSE</code>. The <code>!</code> in front of <code>is.na</code> inverts the logical expression so that we are determining whether each value is NOT an <code>NA</code> (and returns <code>TRUE</code> if the value is not <code>NA</code>). It is common in programming to associate <code>TRUE</code> with <code>1</code> and <code>FALSE</code> with <code>0</code>. So, if we <code>sum</code> the values that are not <code>NA</code>, that is equivalent to counting the number of non-<code>NA</code> observations.</p>
<p>If we want to include the <code>NA</code> values in our relative frequency distribution, we can use the code below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(penguins_clean<span class="sc">$</span>sex, <span class="at">useNA =</span> <span class="st">"ifany"</span>)<span class="sc">/</span><span class="fu">length</span>(penguins_clean<span class="sc">$</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    female       male       &lt;NA&gt; 
0.47965116 0.48837209 0.03197674 </code></pre>
</div>
</div>
<p>We do not know the <code>sex</code> of approximately 3% of the observed penguins.</p>
</section>
<section id="the-summary-function" class="level3" data-number="2.3.3">
<h3 data-number="2.3.3" class="anchored" data-anchor-id="the-summary-function"><span class="header-section-number">2.3.3</span> The <code>summary</code> function</h3>
<p>The <code>summary</code> function provides a simple approach for quickly quantifying the center and spread of each <code>numeric</code> variable in a data frame or determining the frequency distribution of a <code>factor</code> variable. More specifically, the <code>summary</code> function will compute the minimum, 0.25 quantile, mean, median, 0.75 quantile, and maximum of a <code>numeric</code> variable and will return the frequency distribution of a <code>factor</code> variable. This summary will also count the number of <code>NA</code> values in each variable when they are present.</p>
<p>A <code>summary</code> method is available for a <code>data.frame</code> object, which means that we can apply the <code>summary</code> function directly to our <code>penguins_clean</code> data frame, which we do below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(penguins_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      species          island     bill_length      bill_depth   
 adelie   :152   Biscoe   :168   Min.   :32.10   Min.   :13.10  
 chinstrap: 68   Dream    :124   1st Qu.:39.23   1st Qu.:15.60  
 gentoo   :124   Torgersen: 52   Median :44.45   Median :17.30  
                                 Mean   :43.92   Mean   :17.15  
                                 3rd Qu.:48.50   3rd Qu.:18.70  
                                 Max.   :59.60   Max.   :21.50  
                                 NA's   :2       NA's   :2      
 flipper_length    body_mass        sex     
 Min.   :172.0   Min.   :2700   female:165  
 1st Qu.:190.0   1st Qu.:3550   male  :168  
 Median :197.0   Median :4050   NA's  : 11  
 Mean   :200.9   Mean   :4202               
 3rd Qu.:213.0   3rd Qu.:4750               
 Max.   :231.0   Max.   :6300               
 NA's   :2       NA's   :2                  </code></pre>
</div>
</div>
<p>We conveniently get a numeric summary of all of the variables in our data set (we will see different results for variables that are not <code>factor</code> or <code>numeric</code> type). The <code>summary</code> function makes it easy to identify the presence of any <code>NA</code>s in a variable.</p>
</section>
</section>
<section id="visual-summaries-of-data" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="visual-summaries-of-data"><span class="header-section-number">2.4</span> Visual summaries of data</h2>
<p>Visual summaries (i.e., plots) of data are vital to understanding our data prior to modeling. They help us spot data errors, unusual observations, and simple patterns. They also help us communicate the results of our analysis.</p>
<p>We will introduce basic visualization approaches using <strong>base</strong> R functions as well as the popular <strong>ggplot2</strong> package <span class="citation" data-cites="R-ggplot2">(<a href="references.html#ref-R-ggplot2" role="doc-biblioref">Wickham et al. 2024</a>)</span>. It is important to know the basic plotting capabilities of <strong>base</strong> R (particularly the <code>plot</code> function, which has been extended by many packages to provide standard plots for complex objects produced by those packages). However, <strong>ggplot2</strong> is able to produce complex graphics with automated legends in a consistent, systematic way, which provides it advantages over <strong>base</strong> graphics in many contexts.</p>
<p><a href="#tbl-viz-sum" class="quarto-xref">Table&nbsp;<span>2.2</span></a> provides an overview of different plots types that can be used to summarize data, the type of data being summarized, whether the plot is for univariate (one variable), bivariate (two variable), or multivariate (3 or more variables) data, the <strong>base</strong> R functions used to create the plot, and the main <strong>ggplot2</strong> functions needed to create the plot. The table is not intended to be an exhaustive list of useful graphics we should use for data exploration.</p>
<div class="cell">
<div id="tbl-viz-sum" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-viz-sum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2.2: A summary of common plot types used to explore data, the type of variable(s) they summarize, the number of variables summarized, and the <strong>base</strong> R and <strong>ggplot2</strong> functions used to create the plot.
</figcaption>
<div aria-describedby="tbl-viz-sum-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 19%">
<col style="width: 16%">
<col style="width: 23%">
<col style="width: 23%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">plot type</th>
<th style="text-align: left;">variable types</th>
<th style="text-align: left;">number of variables</th>
<th style="text-align: left;">base R</th>
<th style="text-align: left;">ggplot2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">box plot</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">univariate</td>
<td style="text-align: left;"><code>boxplot</code></td>
<td style="text-align: left;"><code>geom_boxplot</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">histogram</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">univariate</td>
<td style="text-align: left;"><code>hist</code></td>
<td style="text-align: left;"><code>geom_histogram</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">density plot</td>
<td style="text-align: left;"><code>numeric</code></td>
<td style="text-align: left;">univariate</td>
<td style="text-align: left;"><code>plot</code>, <code>density</code></td>
<td style="text-align: left;"><code>geom_density</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">bar plot</td>
<td style="text-align: left;"><code>factor</code></td>
<td style="text-align: left;">univariate</td>
<td style="text-align: left;"><code>plot</code> or <code>barplot</code>, <code>table</code></td>
<td style="text-align: left;"><code>geom_bar</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">scatter plot</td>
<td style="text-align: left;">2 <code>numeric</code></td>
<td style="text-align: left;">bivariate</td>
<td style="text-align: left;"><code>plot</code></td>
<td style="text-align: left;"><code>geom_point</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">parallel box plot</td>
<td style="text-align: left;">1 <code>numeric</code>, 1 <code>factor</code></td>
<td style="text-align: left;">bivariate</td>
<td style="text-align: left;"><code>plot</code> or <code>boxplot</code></td>
<td style="text-align: left;"><code>geom_boxplot</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">grouped scatter plot</td>
<td style="text-align: left;">2 <code>numeric</code>, 1 <code>factor</code></td>
<td style="text-align: left;">multivariate</td>
<td style="text-align: left;"><code>plot</code></td>
<td style="text-align: left;"><code>geom_point</code></td>
</tr>
<tr class="even">
<td style="text-align: left;">facetted plots</td>
<td style="text-align: left;">mixed</td>
<td style="text-align: left;">multivariate</td>
<td style="text-align: left;">none</td>
<td style="text-align: left;"><code>facet_wrap</code> or <code>facet_grid</code></td>
</tr>
<tr class="odd">
<td style="text-align: left;">interactive plots</td>
<td style="text-align: left;">mixed</td>
<td style="text-align: left;">multivariate</td>
<td style="text-align: left;">none</td>
<td style="text-align: left;"><code>plotly::ggplotly</code></td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<section id="the-ggplot-recipe" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="the-ggplot-recipe"><span class="header-section-number">2.4.1</span> The ggplot recipe</h3>
<p>There are 4 main components needed to produce a graphic using <strong>ggplot2</strong>.</p>
<ol type="1">
<li>A data frame containing our data.
<ul>
<li>Each column should be a variable and each row should be an observation of data.</li>
</ul></li>
<li>A <code>ggplot</code> object.
<ul>
<li>This is initialized using the <code>ggplot</code> function.</li>
</ul></li>
<li>A geometric object.
<ul>
<li>These are called “geoms” for short.</li>
<li>geoms indicate the geometric object used to visualize the data. E.g., points, lines, polygons etc. More generally, geoms indicate the type of plot that is desired, e.g., histogram, density, or box plot, which are complex geometric objects.</li>
</ul></li>
<li>An aesthetic.
<ul>
<li>An aesthetic mapping indicates what role a variable plays in the plot.</li>
<li>e.g., which variable will play the “x” variable in the plot, the “y” variable in the plot, control the “color” of the observations, etc.</li>
</ul></li>
</ol>
<p>We add “layers” of information to a <code>ggplot</code>, such as geoms, scales, or other customizations, using <code>+</code>.</p>
</section>
<section id="univariate-plots" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="univariate-plots"><span class="header-section-number">2.4.2</span> Univariate plots</h3>
<p>A univariate plot is a plot that only involves a single variable. Examples include bar plots, box plots, histograms, density plots, dot plots, pie charts, etc. (the last two are are generally poor choices.)</p>
<section id="bar-plots" class="level4" data-number="2.4.2.1">
<h4 data-number="2.4.2.1" class="anchored" data-anchor-id="bar-plots"><span class="header-section-number">2.4.2.1</span> Bar plots</h4>
<p>A bar plot (or bar chart) displays the number or proportion of observations in each category of a categorical variable (or using R terminology, each level of a <code>factor</code> variable).</p>
<p>What are we looking for when we create a bar plot? Generally, we are interested in categories that have substantially more or fewer observations than the other categories.</p>
<p>The simplest way to create a bar plot in <strong>base</strong> R is using the <code>plot</code> function on a <code>factor</code> variable. In the code below, we create a bar plot for the <code>island</code> variable of <code>penguins_clean</code>. We use the <code>main</code> argument to add a title to the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(penguins_clean<span class="sc">$</span>island, <span class="at">main =</span> <span class="st">"distribution of island"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that there are approximately 170 penguins from Biscoe island, 125 from Dream island, and 50 from Torgersen island.</p>
<p>Alternatively, we can combine <code>barplot</code> with the <code>table</code> function. We do so below for the <code>sex</code> variable. To account for <code>NA</code>s in the <code>sex</code> variable, we specify <code>useNA = "ifany"</code> in the <code>table</code> function. Also, we specify <code>names.arg = ...</code> to specify the bar names, otherwise the bar for <code>NA</code> will be blank.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(penguins_clean<span class="sc">$</span>sex, <span class="at">useNA =</span> <span class="st">"ifany"</span>), <span class="at">names.arg =</span> <span class="fu">c</span>(<span class="st">"female"</span>, <span class="st">"male"</span>, <span class="st">"NA"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that approximately 48% of the penguins are female, 49% are male, and 3% have an unknown sex.</p>
<p>To create a relative frequency bar plot, we divide the results of <code>table</code> by the number of relevant observations. For this particular example, we could use the code below. We use the <code>length</code> function to determine the number of observations to divide the counts by.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(<span class="fu">table</span>(penguins_clean<span class="sc">$</span>sex, <span class="at">useNA =</span> <span class="st">"ifany"</span>) <span class="sc">/</span> <span class="fu">length</span>(penguins_clean<span class="sc">$</span>sex),</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">names.arg =</span> <span class="fu">c</span>(<span class="st">"female"</span>, <span class="st">"male"</span>, <span class="st">"NA"</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To create a bar plot with <strong>ggplot2</strong>, we first create a basic <code>ggplot</code> object containing our data frame. We must make sure to load the <strong>ggplot2</strong> package prior to creating the plot, otherwise we’ll get errors!</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load ggplot2 package</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a><span class="co"># create generic ggplot object with our data frame</span></span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> penguins_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>gg_penguin</code> is a minimal <code>ggplot</code> object with the raw information needed to produce future graphics. To create a bar plot, we add the geom <code>geom_bar</code> and map the <code>species</code> variable (in this example) to the <code>x</code> aesthetic using the <code>aes</code> function.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create bar plot for species variable</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span> <span class="fu">geom_bar</span>(<span class="fu">aes</span>(<span class="at">x =</span> species))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that there are about 150 Adelie penguins, 70 Chinstrap penguins, and 125 Gentoo penguins.</p>
</section>
<section id="box-plots" class="level4" data-number="2.4.2.2">
<h4 data-number="2.4.2.2" class="anchored" data-anchor-id="box-plots"><span class="header-section-number">2.4.2.2</span> Box plots</h4>
<p>A box plot is a simple graphic showing critical quantiles of a <code>numeric</code> variable, as well as outliers. A box plot indicates the median, 0.25 quantile (Q1), and 0.75 quantile (Q3) of the sample data and extends bars to the largest and smallest observations that are not outliers. Outliers are usually marked with stars or dots. The standard definition of an outlier in the context of box plots is any value that is more than Q3 + 1.5 (Q3 - Q1) and less than Q1 - 1.5 (Q3 - Q1). The box of a box plot extends from Q1 to Q3, with a line in the box indicating the median.</p>
<p>Box plots are useful for identifying outliers and skewness in the variable. However, box plots throw away a lot of information, so we must be cautious in making conclusions about skewness and modality without creating a histogram or density plot of the data.</p>
<p>The <code>boxplot</code> function is the easiest approach for producing a box plot using <strong>base</strong> R. We do so for the <code>body_mass</code> variable below, using the <code>main</code> argument to customize the title of the plot.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(penguins_clean<span class="sc">$</span>body_mass, <span class="at">main =</span> <span class="st">"distribution of body mass"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <code>body_mass</code> variable doesn’t have any outliers. It has perhaps a slight positive skew since the upper tail and upper part of the box are longer than the lower tail and lower part of the box. The median <code>body_mass</code> value is a bit more than 4,000 grams, while 50% of the <code>body_mass</code> values are approximately between 3,500 and 4,750 grams (i.e., between Q1 and Q3). The lightest penguin is less than 3,000 grams, while the heaviest penguin is more than 6,000 grams.</p>
<p>To create a box plot using <strong>ggplot2</strong>, we use <code>geom_boxplot</code>. We create a box plot for the <code>bill_length</code> variable below. We map <code>bill_length</code> to the <code>y</code> aesthetic so that we get a vertically-oriented box plot (mapping it to <code>x</code> will produce a horizontal box plot).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">y =</span> bill_length))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>There are no <code>bill_length</code> outliers. The minimum bill length is approximately 32 mm and the maximum is almost 60 mm. Q1 is approximately 39 mm, the median is approximately 44 mm, and Q3 is approximately 48 mm. It is difficult to assess the skewness of this data. The upper tail is longer than the shorter tail, but the upper box is shorter than the lower box, so the evidence is inconsistent.</p>
</section>
<section id="sec-histograms" class="level4" data-number="2.4.2.3">
<h4 data-number="2.4.2.3" class="anchored" data-anchor-id="sec-histograms"><span class="header-section-number">2.4.2.3</span> Histograms</h4>
<p>A histogram displays the distribution of a <code>numeric</code> variable. A histogram counts the number of values falling into (usually) equal-sized “bins” running from the smallest value to the largest value. The number of bins and width of the bins affect the shape of the histogram.</p>
<p>Histograms are used to assess skewness, modality (the number of clear “peaks” in the plot), and to some extent, outliers.</p>
<p>The <code>hist</code> function creates a histogram of a <code>numeric</code> variable. We create a histogram of <code>bill_length</code> in the code below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(penguins_clean<span class="sc">$</span>bill_length)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The title and x-axis label are visually unappealing, so we use the <code>main</code> and <code>xlab</code> arguments to change them to a blank title and <code>bill length (mm)</code>, respectively. We also increase the number of bins using the <code>breaks</code> argument.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(penguins_clean<span class="sc">$</span>bill_length, <span class="at">main =</span> <span class="st">""</span>, <span class="at">xlab =</span> <span class="st">"bill length (mm)"</span>, <span class="at">breaks =</span> <span class="dv">20</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This distribution of <code>bill_length</code> is bimodal (has two prominent peaks or modes). That is why the box plot of <code>bill_length</code> provided inconsistent evidence of skewness. This also demonstrates why we should not draw conclusions about modality or skewness from numeric summaries alone.</p>
<p>We use <code>geom_histogram</code> to create a histogram using <strong>ggplot2</strong>, mapping the variable of interest to the <code>x</code> aesthetic. We do so for the <code>flipper_length</code> variable below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span> <span class="fu">geom_histogram</span>(<span class="fu">aes</span>(<span class="at">x =</span> flipper_length))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`stat_bin()` using `bins = 30`. Pick better value with `binwidth`.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing non-finite outside the scale range
(`stat_bin()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Flipper length has a bimodal distribution, with prominent peaks centered around 190 and 220 mm.</p>
</section>
<section id="sec-density-plots" class="level4" data-number="2.4.2.4">
<h4 data-number="2.4.2.4" class="anchored" data-anchor-id="sec-density-plots"><span class="header-section-number">2.4.2.4</span> Density plots</h4>
<p>A density plot is similar to a smoothed histogram. The area under a density curve must equal 1. In general, density plots are more visually appealing than histograms, but both communicate similar information. However, density plots can sometimes have problems near the edges of a variable with a fixed upper or lower bound because it is difficult to know how to smooth the data in that case.</p>
<p>We combine the <code>plot</code> and <code>density</code> functions to construct a density plot using <strong>base</strong> R. We do that for the <code>bill_depth</code> variable below. Note the use of <code>na.rm</code> to remove <code>NA</code> values that would otherwise poison the density calculation, and use the <code>main</code> argument to create a blank title.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(penguins_clean<span class="sc">$</span>bill_depth, <span class="at">na.rm =</span> <span class="cn">TRUE</span>), <span class="at">main =</span> <span class="st">""</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <code>bill_depth</code> variable is bimodal with peaks around 14 mm and 18 mm. The graphic also indicates that 342 observations were used to estimate the density and the bandwidth parameter was 0.5533. The bandwidth parameter controls the amount of smoothing and can be changed. Run <code>?stats::density</code> in the Console for more details.</p>
<p>We create a density plot with <strong>ggplot2</strong> using <code>geom_density</code>. We do so for the <code>body_mass</code> variable, mapping it to the <code>x</code> aesthetic.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The <code>body_mass</code> variable is unimodal, with a peak around 3,700 grams. It is also positively skewed.</p>
</section>
</section>
<section id="bivariate-plots" class="level3" data-number="2.4.3">
<h3 data-number="2.4.3" class="anchored" data-anchor-id="bivariate-plots"><span class="header-section-number">2.4.3</span> Bivariate plots</h3>
<p>A bivariate plot is a plot involving two variables. A bivariate plot can involve more than one data type.</p>
<section id="sec-scatter-plots" class="level4" data-number="2.4.3.1">
<h4 data-number="2.4.3.1" class="anchored" data-anchor-id="sec-scatter-plots"><span class="header-section-number">2.4.3.1</span> Scatter plots</h4>
<p>Scatter plots can be used to examine the relationship between two <code>numeric</code> variables.</p>
<p>We use the <code>plot</code> function to create a scatter plot of <code>bill_length</code> versus <code>body_mass</code> (the <code>y</code> variable versus the <code>x</code> variable) using <strong>base</strong> R below. The <code>plot</code> function is very flexible and can be used in multiple ways to produce a scatter plot, but we will use the <code>formula</code> method that takes a formula describing the variables (<code>y ~ x</code>) and the data frame from which the variables come.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a><span class="co"># xlab and ylab are used to customize the x-axis and y-axis labels</span></span>
<span id="cb70-2"><a href="#cb70-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bill_length <span class="sc">~</span> body_mass, <span class="at">data =</span> penguins_clean,</span>
<span id="cb70-3"><a href="#cb70-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"body mass (g)"</span>, <span class="at">ylab =</span> <span class="st">"bill length (mm)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Overall, there is a positive linear relationship between <code>body_mass</code> and <code>bill_length</code>. As <code>body_mass</code> increases, <code>bill_length</code> tends to increase. However, there is a group of points in the upper left part of the scatter plot that don’t fall into the linear pattern quite as well.</p>
<p>The <code>geom_point</code> function is used to create a scatter plot with <strong>ggplot2</strong>. We map the variables to be plotted to the <code>x</code> and <code>y</code> aesthetics. We create a scatter plot of <code>bill_length</code> versus <code>bill_depth</code> using <strong>ggplot2</strong> below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_depth, <span class="at">y =</span> bill_length))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 2 rows containing missing values or values outside the scale range
(`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The plot of <code>bill_length</code> versus <code>bill_depth</code> doesn’t reveal a clear pattern about their association.</p>
</section>
<section id="parallel-box-plots" class="level4" data-number="2.4.3.2">
<h4 data-number="2.4.3.2" class="anchored" data-anchor-id="parallel-box-plots"><span class="header-section-number">2.4.3.2</span> Parallel box plots</h4>
<p>A parallel box plot displays the distribution of a <code>numeric</code> variable split by the level of a <code>factor</code> variable. Specifically, the values of the <code>numeric</code> variable are grouped based on the associated level of a <code>factor</code> variable, and then a box plot is drawn for each group of <code>numeric</code> values. Parallel box plots are useful for determining if the distribution of a <code>numeric</code> variable substantially changes based on whether an observation has a certain level of a <code>factor</code>.</p>
<p>We use the <code>plot</code> function to draw a parallel box plot by associating a <code>numeric</code> variable with a <code>factor</code> variable. Specifically, we use the <code>formula</code> argument of the <code>plot</code> function using the syntax <code>numeric variable ~ factor variable</code> to create a set of vertically-oriented box plots for each level of the <code>factor</code> variable. We can reverse the roles of the variables in the formula to get a horizontal box plots. We create parallel box plots of <code>body_mass</code> versus <code>sex</code> below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(body_mass <span class="sc">~</span> sex, <span class="at">data =</span> penguins_clean)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We can see that the <code>body_mass</code> values tend to be larger for the male penguins compared to the female penguins.</p>
<p>We can produce something similar with <strong>ggplot2</strong> by mapping the <code>numeric</code> variable to the <code>y</code> aesthetic and the <code>factor</code> variable to the <code>x</code> aesthetic inside <code>geom_boxplot</code>. We do so below to compare <code>bill_length</code> for the different penguin <code>species</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> species, <span class="at">y =</span> bill_length))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Based on the parallel box plot of <code>bill_length</code>, we see that the Chinstrap penguins tend to have slightly larger bill lengths than the Gentoo penguins, which typically have larger bill lengths than the Adelie penguins.</p>
</section>
</section>
<section id="multivariate-plots" class="level3" data-number="2.4.4">
<h3 data-number="2.4.4" class="anchored" data-anchor-id="multivariate-plots"><span class="header-section-number">2.4.4</span> Multivariate plots</h3>
<p>A multivariate plot displays relationships between two or more variables (so bivariate plots are technically multivariate plots). We focus on creating multivariate plots with <strong>ggplot2</strong>. While the same graphics can be created with <strong>base</strong> R, it is easier to create informative multivariate graphics with <strong>ggplot2</strong>.</p>
<section id="grouped-scatter-plot" class="level4" data-number="2.4.4.1">
<h4 data-number="2.4.4.1" class="anchored" data-anchor-id="grouped-scatter-plot"><span class="header-section-number">2.4.4.1</span> Grouped scatter plot</h4>
<p>A grouped scatter plot is a scatter plot that uses colors or symbols (or both) to indicate the level of a <code>factor</code> variable that each point corresponds to. We can actually use more than one <code>factor</code> variable, but interpreting the plot becomes more difficult. The most common way to create a grouped scatter plot with <strong>ggplot2</strong> is to map a <code>factor</code> variable to the <code>color</code> or <code>shape</code> aesthetic of <code>geom_point</code>. <strong>ggplot2</strong> will automatically map the <code>factor</code> variable to unique colors or shapes and then describe the mapping in a legend (this process is known as “scaling”). In the example below, we create a scatter plot of <code>flipper_length</code> versus <code>body_mass</code> that distinguishes the different <code>species</code> using <code>color</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass, <span class="at">y =</span> flipper_length, <span class="at">color =</span> species))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The flipper length and body mass of Gentoo penguins tend to be noticeably larger than the other two species. Chinstrap and Adelie penguins tend to have similar flipper length and body mass, with Chinstrap penguins tending to have slightly longer flipper length.</p>
<p>We can improve the graphic above can be made better in two ways. 1. Using better colors, and 2. Using more than one visual approach to distinguish the levels of the <code>factor</code> variable. The grouped scatter plot uses both red and green colors, which may be difficult to distinguish for individuals with certain forms of colorblindness. We should use a more friendly color palette. An excellent resource for choosing a color palette is <a href="https://colorbrewer2.org">https://colorbrewer2.org</a> (<span class="citation" data-cites="brewer">Brewer (<a href="references.html#ref-brewer" role="doc-biblioref">2022</a>)</span>). The Color Brewer website simplifies choosing a color palette based on certain desired characteristics such as whether the palette is colorblind-friendly, printer friendly, etc. The recommend palettes can be accessed using the <code>scale_color_brewer</code> function. We use a colorblind-friendly palette below. We also changes the x-axis label, y-axis label, and title using the <code>xlab</code>, <code>ylab</code>, and <code>ggtitle</code> functions respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass, <span class="at">y =</span> flipper_length, <span class="at">color =</span> species, <span class="at">shape =</span> species)) <span class="sc">+</span></span>
<span id="cb76-3"><a href="#cb76-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">type =</span> <span class="st">"qual"</span>, <span class="at">palette =</span> <span class="st">"Dark2"</span>) <span class="sc">+</span></span>
<span id="cb76-4"><a href="#cb76-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"body mass (g)"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"flipper length (mm)"</span>) <span class="sc">+</span></span>
<span id="cb76-5"><a href="#cb76-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"body mass versus flipper length by species"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="facetted-plots-and-alternatives" class="level4" data-number="2.4.4.2">
<h4 data-number="2.4.4.2" class="anchored" data-anchor-id="facetted-plots-and-alternatives"><span class="header-section-number">2.4.4.2</span> Facetted plots (and alternatives)</h4>
<p>Facetting creates separate panels (facets) of plots based on one or more facetting variables. The key functions to do this with <strong>ggplot2</strong> are the <code>facet_grid</code> and <code>facet_wrap</code> functions. <code>facet_grid</code> is used to create a grid of plots based on one or two <code>factor</code> variables, while <code>facet_wrap</code> wraps facets of panels around the plot. Below, we facet scatter plots of <code>bill_length</code> versus <code>bill_depth</code> by <code>species</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span> <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> bill_depth, <span class="at">y =</span> bill_length)) <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span> species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Whereas we previously couldn’t discern a clear relationship between bill length and depth based on a single scatter plot, facetting by <code>species</code> makes it clear there is a positive relationship between <code>bill_length</code> and <code>bill_depth</code> after accounting for <code>species</code>. We could have used a grouped scatter plot for the same purpose.</p>
<p>A simpler facetting example would be to facet density plots of <code>body_mass</code> by <code>sex</code> as shown below.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a>gg_penguin <span class="sc">+</span> <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass)) <span class="sc">+</span> <span class="fu">facet_grid</span>(<span class="sc">~</span>sex)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot is a bit difficult to interpret. We see that body mass is bimodal for the males and females. Perhaps this is related to <code>species</code>. Since the density plots are in different panels, its a bit tricky to see how they relate to each other. Also, the <code>NA</code> panel is probably not needed.</p>
<p>To get rid of the <code>NA</code> panel, we need to remove all of the observations with <code>NA</code> values. We do this below, using <code>subset</code> to select the desired columns and then using <code>na.omit</code> to remove any rows that have <code>NA</code> values for <code>body_mass</code>, <code>sex</code>, or <code>species</code>. Note that order matters here because <code>na.omit</code> removes any observation of the data frame that has an <code>NA</code> value. We save the filtered object as <code>penguins_temp</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a>penguins_temp <span class="ot">&lt;-</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a>  penguins_clean <span class="sc">|&gt;</span></span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">subset</span>(<span class="at">select =</span> <span class="fu">c</span>(body_mass, sex, species)) <span class="sc">|&gt;</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">na.omit</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In the next graphic, we create density plots of the <code>body_mass</code> variable. However, we use the <code>fill</code> aesthetic to scale the <code>sex</code> variable so that the we distinguish the densities of male and female penguins with different colors. We set the <code>alpha</code> argument to 0.5 OUTSIDE the <code>aes</code> function (because it is being manually specified) so that the colors are translucent and blend. We also facet by species to see what the patterns look like for the different species.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(<span class="at">data =</span> penguins_temp) <span class="sc">+</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass, <span class="at">fill =</span> sex), <span class="at">alpha =</span> <span class="fl">0.5</span>) <span class="sc">+</span></span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_grid</span>(<span class="sc">~</span> species)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="data-exploration_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We see that for all species, the body mass of the males tends to be larger than the females.</p>
<p>The examples above provide a small taste of the complex graphics we can create with <strong>ggplot2</strong> using only a few lines of code.</p>
</section>
<section id="interactive-graphics" class="level4" data-number="2.4.4.3">
<h4 data-number="2.4.4.3" class="anchored" data-anchor-id="interactive-graphics"><span class="header-section-number">2.4.4.3</span> Interactive graphics</h4>
<p>There are many tools for creating interactive graphics in R. We have found the <strong><code>ggiraph</code></strong> package <span class="citation" data-cites="R-ggiraph">(<a href="references.html#ref-R-ggiraph" role="doc-biblioref">Gohel and Skintzos 2024</a>)</span> useful for creating interactive graphics based on <strong>ggplot2</strong>. However, it is a bit too complex to discuss here.</p>
<p>The <strong><code>plotly</code></strong> package <span class="citation" data-cites="R-plotly">(<a href="references.html#ref-R-plotly" role="doc-biblioref">Sievert et al. 2024</a>)</span> provides the capabilities of plotly <span class="citation" data-cites="plotly">(<a href="references.html#ref-plotly" role="doc-biblioref">Plotly Technologies Inc. 2015</a>, <a href="references.html(https://plotly.com/)" role="doc-biblioref">https://plotly.com/</a>)</span>, a well-known tool for creating interactive scientific plots, through R. The <code>ggplotly</code> function will instantly make a <code>ggplot</code> interactive (though we may need to customize it for our needs). We provide two examples below.</p>
<p>First, we load the <strong><code>plotly</code></strong> package to have access to the <code>ggplotly</code> function. We then take our previous grouped scatter plot that plotted <code>flipper_length</code> versus <code>body_mass</code> while distinguishing by <code>species</code> and assign it the name <code>ggi</code>. We then use the <code>ggplotly</code> function to make the graphic interactive. When we hover over a point, the plot interactively provides the exact <code>body_mass</code> value, <code>flipper_length</code> value, and <code>species</code> of the observation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># load plotly package</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(plotly)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="co"># assign grouped scatter plot name</span></span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a>ggi <span class="ot">&lt;-</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a>  gg_penguin <span class="sc">+</span></span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">x =</span> body_mass, <span class="at">y =</span> flipper_length, <span class="at">color =</span> species, <span class="at">shape =</span> species)) <span class="sc">+</span></span>
<span id="cb81-7"><a href="#cb81-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_brewer</span>(<span class="at">type =</span> <span class="st">"qual"</span>, <span class="at">palette =</span> <span class="st">"Dark2"</span>) <span class="sc">+</span></span>
<span id="cb81-8"><a href="#cb81-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"body mass (g)"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"flipper length (mm)"</span>) <span class="sc">+</span></span>
<span id="cb81-9"><a href="#cb81-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"body mass versus flipper length by species"</span>)</span>
<span id="cb81-10"><a href="#cb81-10" aria-hidden="true" tabindex="-1"></a><span class="co"># make plot interactive</span></span>
<span id="cb81-11"><a href="#cb81-11" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(ggi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-4fbe7973703f10aa6031" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-4fbe7973703f10aa6031">{"x":{"data":[{"x":[3750,3800,3250,null,3450,3650,3625,4675,3475,4250,3300,3700,3200,3800,4400,3700,3450,4500,3325,4200,3400,3600,3800,3950,3800,3800,3550,3200,3150,3950,3250,3900,3300,3900,3325,4150,3950,3550,3300,4650,3150,3900,3100,4400,3000,4600,3425,2975,3450,4150,3500,4300,3450,4050,2900,3700,3550,3800,2850,3750,3150,4400,3600,4050,2850,3950,3350,4100,3050,4450,3600,3900,3550,4150,3700,4250,3700,3900,3550,4000,3200,4700,3800,4200,3350,3550,3800,3500,3950,3600,3550,4300,3400,4450,3300,4300,3700,4350,2900,4100,3725,4725,3075,4250,2925,3550,3750,3900,3175,4775,3825,4600,3200,4275,3900,4075,2900,3775,3350,3325,3150,3500,3450,3875,3050,4000,3275,4300,3050,4000,3325,3500,3500,4475,3425,3900,3175,3975,3400,4250,3400,3475,3050,3725,3000,3650,4250,3475,3450,3750,3700,4000],"y":[181,186,195,null,193,190,181,195,193,190,186,180,182,191,198,185,195,197,184,194,174,180,189,185,180,187,183,187,172,180,178,178,188,184,195,196,190,180,181,184,182,195,186,196,185,190,182,179,190,191,186,188,190,200,187,191,186,193,181,194,185,195,185,192,184,192,195,188,190,198,190,190,196,197,190,195,191,184,187,195,189,196,187,193,191,194,190,189,189,190,202,205,185,186,187,208,190,196,178,192,192,203,183,190,193,184,199,190,181,197,198,191,193,197,191,196,188,199,189,189,187,198,176,202,186,199,191,195,191,210,190,197,193,199,187,190,191,200,185,193,193,187,188,190,192,185,190,184,195,193,187,201],"text":["body_mass: 3750<br />flipper_length: 181<br />species: adelie<br />species: adelie","body_mass: 3800<br />flipper_length: 186<br />species: adelie<br />species: adelie","body_mass: 3250<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass:   NA<br />flipper_length:  NA<br />species: adelie<br />species: adelie","body_mass: 3450<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 3650<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3625<br />flipper_length: 181<br />species: adelie<br />species: adelie","body_mass: 4675<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 3475<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 4250<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3300<br />flipper_length: 186<br />species: adelie<br />species: adelie","body_mass: 3700<br />flipper_length: 180<br />species: adelie<br />species: adelie","body_mass: 3200<br />flipper_length: 182<br />species: adelie<br />species: adelie","body_mass: 3800<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 4400<br />flipper_length: 198<br />species: adelie<br />species: adelie","body_mass: 3700<br />flipper_length: 185<br />species: adelie<br />species: adelie","body_mass: 3450<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 4500<br />flipper_length: 197<br />species: adelie<br />species: adelie","body_mass: 3325<br />flipper_length: 184<br />species: adelie<br />species: adelie","body_mass: 4200<br />flipper_length: 194<br />species: adelie<br />species: adelie","body_mass: 3400<br />flipper_length: 174<br />species: adelie<br />species: adelie","body_mass: 3600<br />flipper_length: 180<br />species: adelie<br />species: adelie","body_mass: 3800<br />flipper_length: 189<br />species: adelie<br />species: adelie","body_mass: 3950<br />flipper_length: 185<br />species: adelie<br />species: adelie","body_mass: 3800<br />flipper_length: 180<br />species: adelie<br />species: adelie","body_mass: 3800<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 3550<br />flipper_length: 183<br />species: adelie<br />species: adelie","body_mass: 3200<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 3150<br />flipper_length: 172<br />species: adelie<br />species: adelie","body_mass: 3950<br />flipper_length: 180<br />species: adelie<br />species: adelie","body_mass: 3250<br />flipper_length: 178<br />species: adelie<br />species: adelie","body_mass: 3900<br />flipper_length: 178<br />species: adelie<br />species: adelie","body_mass: 3300<br />flipper_length: 188<br />species: adelie<br />species: adelie","body_mass: 3900<br />flipper_length: 184<br />species: adelie<br />species: adelie","body_mass: 3325<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 4150<br />flipper_length: 196<br />species: adelie<br />species: adelie","body_mass: 3950<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3550<br />flipper_length: 180<br />species: adelie<br />species: adelie","body_mass: 3300<br />flipper_length: 181<br />species: adelie<br />species: adelie","body_mass: 4650<br />flipper_length: 184<br />species: adelie<br />species: adelie","body_mass: 3150<br />flipper_length: 182<br />species: adelie<br />species: adelie","body_mass: 3900<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 3100<br />flipper_length: 186<br />species: adelie<br />species: adelie","body_mass: 4400<br />flipper_length: 196<br />species: adelie<br />species: adelie","body_mass: 3000<br />flipper_length: 185<br />species: adelie<br />species: adelie","body_mass: 4600<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3425<br />flipper_length: 182<br />species: adelie<br />species: adelie","body_mass: 2975<br />flipper_length: 179<br />species: adelie<br />species: adelie","body_mass: 3450<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 4150<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 3500<br />flipper_length: 186<br />species: adelie<br />species: adelie","body_mass: 4300<br />flipper_length: 188<br />species: adelie<br />species: adelie","body_mass: 3450<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 4050<br />flipper_length: 200<br />species: adelie<br />species: adelie","body_mass: 2900<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 3700<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 3550<br />flipper_length: 186<br />species: adelie<br />species: adelie","body_mass: 3800<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 2850<br />flipper_length: 181<br />species: adelie<br />species: adelie","body_mass: 3750<br />flipper_length: 194<br />species: adelie<br />species: adelie","body_mass: 3150<br />flipper_length: 185<br />species: adelie<br />species: adelie","body_mass: 4400<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 3600<br />flipper_length: 185<br />species: adelie<br />species: adelie","body_mass: 4050<br />flipper_length: 192<br />species: adelie<br />species: adelie","body_mass: 2850<br />flipper_length: 184<br />species: adelie<br />species: adelie","body_mass: 3950<br />flipper_length: 192<br />species: adelie<br />species: adelie","body_mass: 3350<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 4100<br />flipper_length: 188<br />species: adelie<br />species: adelie","body_mass: 3050<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 4450<br />flipper_length: 198<br />species: adelie<br />species: adelie","body_mass: 3600<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3900<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3550<br />flipper_length: 196<br />species: adelie<br />species: adelie","body_mass: 4150<br />flipper_length: 197<br />species: adelie<br />species: adelie","body_mass: 3700<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 4250<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 3700<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 3900<br />flipper_length: 184<br />species: adelie<br />species: adelie","body_mass: 3550<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 4000<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 3200<br />flipper_length: 189<br />species: adelie<br />species: adelie","body_mass: 4700<br />flipper_length: 196<br />species: adelie<br />species: adelie","body_mass: 3800<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 4200<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 3350<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 3550<br />flipper_length: 194<br />species: adelie<br />species: adelie","body_mass: 3800<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3500<br />flipper_length: 189<br />species: adelie<br />species: adelie","body_mass: 3950<br />flipper_length: 189<br />species: adelie<br />species: adelie","body_mass: 3600<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3550<br />flipper_length: 202<br />species: adelie<br />species: adelie","body_mass: 4300<br />flipper_length: 205<br />species: adelie<br />species: adelie","body_mass: 3400<br />flipper_length: 185<br />species: adelie<br />species: adelie","body_mass: 4450<br />flipper_length: 186<br />species: adelie<br />species: adelie","body_mass: 3300<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 4300<br />flipper_length: 208<br />species: adelie<br />species: adelie","body_mass: 3700<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 4350<br />flipper_length: 196<br />species: adelie<br />species: adelie","body_mass: 2900<br />flipper_length: 178<br />species: adelie<br />species: adelie","body_mass: 4100<br />flipper_length: 192<br />species: adelie<br />species: adelie","body_mass: 3725<br />flipper_length: 192<br />species: adelie<br />species: adelie","body_mass: 4725<br />flipper_length: 203<br />species: adelie<br />species: adelie","body_mass: 3075<br />flipper_length: 183<br />species: adelie<br />species: adelie","body_mass: 4250<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 2925<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 3550<br />flipper_length: 184<br />species: adelie<br />species: adelie","body_mass: 3750<br />flipper_length: 199<br />species: adelie<br />species: adelie","body_mass: 3900<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3175<br />flipper_length: 181<br />species: adelie<br />species: adelie","body_mass: 4775<br />flipper_length: 197<br />species: adelie<br />species: adelie","body_mass: 3825<br />flipper_length: 198<br />species: adelie<br />species: adelie","body_mass: 4600<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 3200<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 4275<br />flipper_length: 197<br />species: adelie<br />species: adelie","body_mass: 3900<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 4075<br />flipper_length: 196<br />species: adelie<br />species: adelie","body_mass: 2900<br />flipper_length: 188<br />species: adelie<br />species: adelie","body_mass: 3775<br />flipper_length: 199<br />species: adelie<br />species: adelie","body_mass: 3350<br />flipper_length: 189<br />species: adelie<br />species: adelie","body_mass: 3325<br />flipper_length: 189<br />species: adelie<br />species: adelie","body_mass: 3150<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 3500<br />flipper_length: 198<br />species: adelie<br />species: adelie","body_mass: 3450<br />flipper_length: 176<br />species: adelie<br />species: adelie","body_mass: 3875<br />flipper_length: 202<br />species: adelie<br />species: adelie","body_mass: 3050<br />flipper_length: 186<br />species: adelie<br />species: adelie","body_mass: 4000<br />flipper_length: 199<br />species: adelie<br />species: adelie","body_mass: 3275<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 4300<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 3050<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 4000<br />flipper_length: 210<br />species: adelie<br />species: adelie","body_mass: 3325<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3500<br />flipper_length: 197<br />species: adelie<br />species: adelie","body_mass: 3500<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 4475<br />flipper_length: 199<br />species: adelie<br />species: adelie","body_mass: 3425<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 3900<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3175<br />flipper_length: 191<br />species: adelie<br />species: adelie","body_mass: 3975<br />flipper_length: 200<br />species: adelie<br />species: adelie","body_mass: 3400<br />flipper_length: 185<br />species: adelie<br />species: adelie","body_mass: 4250<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 3400<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 3475<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 3050<br />flipper_length: 188<br />species: adelie<br />species: adelie","body_mass: 3725<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3000<br />flipper_length: 192<br />species: adelie<br />species: adelie","body_mass: 3650<br />flipper_length: 185<br />species: adelie<br />species: adelie","body_mass: 4250<br />flipper_length: 190<br />species: adelie<br />species: adelie","body_mass: 3475<br />flipper_length: 184<br />species: adelie<br />species: adelie","body_mass: 3450<br />flipper_length: 195<br />species: adelie<br />species: adelie","body_mass: 3750<br />flipper_length: 193<br />species: adelie<br />species: adelie","body_mass: 3700<br />flipper_length: 187<br />species: adelie<br />species: adelie","body_mass: 4000<br />flipper_length: 201<br />species: adelie<br />species: adelie"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(27,158,119,1)","opacity":1,"size":5.6692913385826778,"symbol":"circle","line":{"width":1.8897637795275593,"color":"rgba(27,158,119,1)"}},"hoveron":"points","name":"adelie","legendgroup":"adelie","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[3500,3900,3650,3525,3725,3950,3250,3750,4150,3700,3800,3775,3700,4050,3575,4050,3300,3700,3450,4400,3600,3400,2900,3800,3300,4150,3400,3800,3700,4550,3200,4300,3350,4100,3600,3900,3850,4800,2700,4500,3950,3650,3550,3500,3675,4450,3400,4300,3250,3675,3325,3950,3600,4050,3350,3450,3250,4050,3800,3525,3950,3650,3650,4000,3400,3775,4100,3775],"y":[192,196,193,188,197,198,178,197,195,198,193,194,185,201,190,201,197,181,190,195,181,191,187,193,195,197,200,200,191,205,187,201,187,203,195,199,195,210,192,205,210,187,196,196,196,201,190,212,187,198,199,201,193,203,187,197,191,203,202,194,206,189,195,207,202,193,210,198],"text":["body_mass: 3500<br />flipper_length: 192<br />species: chinstrap<br />species: chinstrap","body_mass: 3900<br />flipper_length: 196<br />species: chinstrap<br />species: chinstrap","body_mass: 3650<br />flipper_length: 193<br />species: chinstrap<br />species: chinstrap","body_mass: 3525<br />flipper_length: 188<br />species: chinstrap<br />species: chinstrap","body_mass: 3725<br />flipper_length: 197<br />species: chinstrap<br />species: chinstrap","body_mass: 3950<br />flipper_length: 198<br />species: chinstrap<br />species: chinstrap","body_mass: 3250<br />flipper_length: 178<br />species: chinstrap<br />species: chinstrap","body_mass: 3750<br />flipper_length: 197<br />species: chinstrap<br />species: chinstrap","body_mass: 4150<br />flipper_length: 195<br />species: chinstrap<br />species: chinstrap","body_mass: 3700<br />flipper_length: 198<br />species: chinstrap<br />species: chinstrap","body_mass: 3800<br />flipper_length: 193<br />species: chinstrap<br />species: chinstrap","body_mass: 3775<br />flipper_length: 194<br />species: chinstrap<br />species: chinstrap","body_mass: 3700<br />flipper_length: 185<br />species: chinstrap<br />species: chinstrap","body_mass: 4050<br />flipper_length: 201<br />species: chinstrap<br />species: chinstrap","body_mass: 3575<br />flipper_length: 190<br />species: chinstrap<br />species: chinstrap","body_mass: 4050<br />flipper_length: 201<br />species: chinstrap<br />species: chinstrap","body_mass: 3300<br />flipper_length: 197<br />species: chinstrap<br />species: chinstrap","body_mass: 3700<br />flipper_length: 181<br />species: chinstrap<br />species: chinstrap","body_mass: 3450<br />flipper_length: 190<br />species: chinstrap<br />species: chinstrap","body_mass: 4400<br />flipper_length: 195<br />species: chinstrap<br />species: chinstrap","body_mass: 3600<br />flipper_length: 181<br />species: chinstrap<br />species: chinstrap","body_mass: 3400<br />flipper_length: 191<br />species: chinstrap<br />species: chinstrap","body_mass: 2900<br />flipper_length: 187<br />species: chinstrap<br />species: chinstrap","body_mass: 3800<br />flipper_length: 193<br />species: chinstrap<br />species: chinstrap","body_mass: 3300<br />flipper_length: 195<br />species: chinstrap<br />species: chinstrap","body_mass: 4150<br />flipper_length: 197<br />species: chinstrap<br />species: chinstrap","body_mass: 3400<br />flipper_length: 200<br />species: chinstrap<br />species: chinstrap","body_mass: 3800<br />flipper_length: 200<br />species: chinstrap<br />species: chinstrap","body_mass: 3700<br />flipper_length: 191<br />species: chinstrap<br />species: chinstrap","body_mass: 4550<br />flipper_length: 205<br />species: chinstrap<br />species: chinstrap","body_mass: 3200<br />flipper_length: 187<br />species: chinstrap<br />species: chinstrap","body_mass: 4300<br />flipper_length: 201<br />species: chinstrap<br />species: chinstrap","body_mass: 3350<br />flipper_length: 187<br />species: chinstrap<br />species: chinstrap","body_mass: 4100<br />flipper_length: 203<br />species: chinstrap<br />species: chinstrap","body_mass: 3600<br />flipper_length: 195<br />species: chinstrap<br />species: chinstrap","body_mass: 3900<br />flipper_length: 199<br />species: chinstrap<br />species: chinstrap","body_mass: 3850<br />flipper_length: 195<br />species: chinstrap<br />species: chinstrap","body_mass: 4800<br />flipper_length: 210<br />species: chinstrap<br />species: chinstrap","body_mass: 2700<br />flipper_length: 192<br />species: chinstrap<br />species: chinstrap","body_mass: 4500<br />flipper_length: 205<br />species: chinstrap<br />species: chinstrap","body_mass: 3950<br />flipper_length: 210<br />species: chinstrap<br />species: chinstrap","body_mass: 3650<br />flipper_length: 187<br />species: chinstrap<br />species: chinstrap","body_mass: 3550<br />flipper_length: 196<br />species: chinstrap<br />species: chinstrap","body_mass: 3500<br />flipper_length: 196<br />species: chinstrap<br />species: chinstrap","body_mass: 3675<br />flipper_length: 196<br />species: chinstrap<br />species: chinstrap","body_mass: 4450<br />flipper_length: 201<br />species: chinstrap<br />species: chinstrap","body_mass: 3400<br />flipper_length: 190<br />species: chinstrap<br />species: chinstrap","body_mass: 4300<br />flipper_length: 212<br />species: chinstrap<br />species: chinstrap","body_mass: 3250<br />flipper_length: 187<br />species: chinstrap<br />species: chinstrap","body_mass: 3675<br />flipper_length: 198<br />species: chinstrap<br />species: chinstrap","body_mass: 3325<br />flipper_length: 199<br />species: chinstrap<br />species: chinstrap","body_mass: 3950<br />flipper_length: 201<br />species: chinstrap<br />species: chinstrap","body_mass: 3600<br />flipper_length: 193<br />species: chinstrap<br />species: chinstrap","body_mass: 4050<br />flipper_length: 203<br />species: chinstrap<br />species: chinstrap","body_mass: 3350<br />flipper_length: 187<br />species: chinstrap<br />species: chinstrap","body_mass: 3450<br />flipper_length: 197<br />species: chinstrap<br />species: chinstrap","body_mass: 3250<br />flipper_length: 191<br />species: chinstrap<br />species: chinstrap","body_mass: 4050<br />flipper_length: 203<br />species: chinstrap<br />species: chinstrap","body_mass: 3800<br />flipper_length: 202<br />species: chinstrap<br />species: chinstrap","body_mass: 3525<br />flipper_length: 194<br />species: chinstrap<br />species: chinstrap","body_mass: 3950<br />flipper_length: 206<br />species: chinstrap<br />species: chinstrap","body_mass: 3650<br />flipper_length: 189<br />species: chinstrap<br />species: chinstrap","body_mass: 3650<br />flipper_length: 195<br />species: chinstrap<br />species: chinstrap","body_mass: 4000<br />flipper_length: 207<br />species: chinstrap<br />species: chinstrap","body_mass: 3400<br />flipper_length: 202<br />species: chinstrap<br />species: chinstrap","body_mass: 3775<br />flipper_length: 193<br />species: chinstrap<br />species: chinstrap","body_mass: 4100<br />flipper_length: 210<br />species: chinstrap<br />species: chinstrap","body_mass: 3775<br />flipper_length: 198<br />species: chinstrap<br />species: chinstrap"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(217,95,2,1)","opacity":1,"size":5.6692913385826778,"symbol":"triangle-up","line":{"width":1.8897637795275593,"color":"rgba(217,95,2,1)"}},"hoveron":"points","name":"chinstrap","legendgroup":"chinstrap","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null},{"x":[4500,5700,4450,5700,5400,4550,4800,5200,4400,5150,4650,5550,4650,5850,4200,5850,4150,6300,4800,5350,5700,5000,4400,5050,5000,5100,4100,5650,4600,5550,5250,4700,5050,6050,5150,5400,4950,5250,4350,5350,3950,5700,4300,4750,5550,4900,4200,5400,5100,5300,4850,5300,4400,5000,4900,5050,4300,5000,4450,5550,4200,5300,4400,5650,4700,5700,4650,5800,4700,5550,4750,5000,5100,5200,4700,5800,4600,6000,4750,5950,4625,5450,4725,5350,4750,5600,4600,5300,4875,5550,4950,5400,4750,5650,4850,5200,4925,4875,4625,5250,4850,5600,4975,5500,4725,5500,4700,5500,4575,5500,5000,5950,4650,5500,4375,5850,4875,6000,4925,null,4850,5750,5200,5400],"y":[211,230,210,218,215,210,211,219,209,215,214,216,214,213,210,217,210,221,209,222,218,215,213,215,215,215,216,215,210,220,222,209,207,230,220,220,213,219,208,208,208,225,210,216,222,217,210,225,213,215,210,220,210,225,217,220,208,220,208,224,208,221,214,231,219,230,214,229,220,223,216,221,221,217,216,230,209,220,215,223,212,221,212,224,212,228,218,218,212,230,218,228,212,224,214,226,216,222,203,225,219,228,215,228,216,215,210,219,208,209,216,229,213,230,217,230,217,222,214,null,215,222,212,213],"text":["body_mass: 4500<br />flipper_length: 211<br />species: gentoo<br />species: gentoo","body_mass: 5700<br />flipper_length: 230<br />species: gentoo<br />species: gentoo","body_mass: 4450<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 5700<br />flipper_length: 218<br />species: gentoo<br />species: gentoo","body_mass: 5400<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 4550<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 4800<br />flipper_length: 211<br />species: gentoo<br />species: gentoo","body_mass: 5200<br />flipper_length: 219<br />species: gentoo<br />species: gentoo","body_mass: 4400<br />flipper_length: 209<br />species: gentoo<br />species: gentoo","body_mass: 5150<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 4650<br />flipper_length: 214<br />species: gentoo<br />species: gentoo","body_mass: 5550<br />flipper_length: 216<br />species: gentoo<br />species: gentoo","body_mass: 4650<br />flipper_length: 214<br />species: gentoo<br />species: gentoo","body_mass: 5850<br />flipper_length: 213<br />species: gentoo<br />species: gentoo","body_mass: 4200<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 5850<br />flipper_length: 217<br />species: gentoo<br />species: gentoo","body_mass: 4150<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 6300<br />flipper_length: 221<br />species: gentoo<br />species: gentoo","body_mass: 4800<br />flipper_length: 209<br />species: gentoo<br />species: gentoo","body_mass: 5350<br />flipper_length: 222<br />species: gentoo<br />species: gentoo","body_mass: 5700<br />flipper_length: 218<br />species: gentoo<br />species: gentoo","body_mass: 5000<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 4400<br />flipper_length: 213<br />species: gentoo<br />species: gentoo","body_mass: 5050<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 5000<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 5100<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 4100<br />flipper_length: 216<br />species: gentoo<br />species: gentoo","body_mass: 5650<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 4600<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 5550<br />flipper_length: 220<br />species: gentoo<br />species: gentoo","body_mass: 5250<br />flipper_length: 222<br />species: gentoo<br />species: gentoo","body_mass: 4700<br />flipper_length: 209<br />species: gentoo<br />species: gentoo","body_mass: 5050<br />flipper_length: 207<br />species: gentoo<br />species: gentoo","body_mass: 6050<br />flipper_length: 230<br />species: gentoo<br />species: gentoo","body_mass: 5150<br />flipper_length: 220<br />species: gentoo<br />species: gentoo","body_mass: 5400<br />flipper_length: 220<br />species: gentoo<br />species: gentoo","body_mass: 4950<br />flipper_length: 213<br />species: gentoo<br />species: gentoo","body_mass: 5250<br />flipper_length: 219<br />species: gentoo<br />species: gentoo","body_mass: 4350<br />flipper_length: 208<br />species: gentoo<br />species: gentoo","body_mass: 5350<br />flipper_length: 208<br />species: gentoo<br />species: gentoo","body_mass: 3950<br />flipper_length: 208<br />species: gentoo<br />species: gentoo","body_mass: 5700<br />flipper_length: 225<br />species: gentoo<br />species: gentoo","body_mass: 4300<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 4750<br />flipper_length: 216<br />species: gentoo<br />species: gentoo","body_mass: 5550<br />flipper_length: 222<br />species: gentoo<br />species: gentoo","body_mass: 4900<br />flipper_length: 217<br />species: gentoo<br />species: gentoo","body_mass: 4200<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 5400<br />flipper_length: 225<br />species: gentoo<br />species: gentoo","body_mass: 5100<br />flipper_length: 213<br />species: gentoo<br />species: gentoo","body_mass: 5300<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 4850<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 5300<br />flipper_length: 220<br />species: gentoo<br />species: gentoo","body_mass: 4400<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 5000<br />flipper_length: 225<br />species: gentoo<br />species: gentoo","body_mass: 4900<br />flipper_length: 217<br />species: gentoo<br />species: gentoo","body_mass: 5050<br />flipper_length: 220<br />species: gentoo<br />species: gentoo","body_mass: 4300<br />flipper_length: 208<br />species: gentoo<br />species: gentoo","body_mass: 5000<br />flipper_length: 220<br />species: gentoo<br />species: gentoo","body_mass: 4450<br />flipper_length: 208<br />species: gentoo<br />species: gentoo","body_mass: 5550<br />flipper_length: 224<br />species: gentoo<br />species: gentoo","body_mass: 4200<br />flipper_length: 208<br />species: gentoo<br />species: gentoo","body_mass: 5300<br />flipper_length: 221<br />species: gentoo<br />species: gentoo","body_mass: 4400<br />flipper_length: 214<br />species: gentoo<br />species: gentoo","body_mass: 5650<br />flipper_length: 231<br />species: gentoo<br />species: gentoo","body_mass: 4700<br />flipper_length: 219<br />species: gentoo<br />species: gentoo","body_mass: 5700<br />flipper_length: 230<br />species: gentoo<br />species: gentoo","body_mass: 4650<br />flipper_length: 214<br />species: gentoo<br />species: gentoo","body_mass: 5800<br />flipper_length: 229<br />species: gentoo<br />species: gentoo","body_mass: 4700<br />flipper_length: 220<br />species: gentoo<br />species: gentoo","body_mass: 5550<br />flipper_length: 223<br />species: gentoo<br />species: gentoo","body_mass: 4750<br />flipper_length: 216<br />species: gentoo<br />species: gentoo","body_mass: 5000<br />flipper_length: 221<br />species: gentoo<br />species: gentoo","body_mass: 5100<br />flipper_length: 221<br />species: gentoo<br />species: gentoo","body_mass: 5200<br />flipper_length: 217<br />species: gentoo<br />species: gentoo","body_mass: 4700<br />flipper_length: 216<br />species: gentoo<br />species: gentoo","body_mass: 5800<br />flipper_length: 230<br />species: gentoo<br />species: gentoo","body_mass: 4600<br />flipper_length: 209<br />species: gentoo<br />species: gentoo","body_mass: 6000<br />flipper_length: 220<br />species: gentoo<br />species: gentoo","body_mass: 4750<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 5950<br />flipper_length: 223<br />species: gentoo<br />species: gentoo","body_mass: 4625<br />flipper_length: 212<br />species: gentoo<br />species: gentoo","body_mass: 5450<br />flipper_length: 221<br />species: gentoo<br />species: gentoo","body_mass: 4725<br />flipper_length: 212<br />species: gentoo<br />species: gentoo","body_mass: 5350<br />flipper_length: 224<br />species: gentoo<br />species: gentoo","body_mass: 4750<br />flipper_length: 212<br />species: gentoo<br />species: gentoo","body_mass: 5600<br />flipper_length: 228<br />species: gentoo<br />species: gentoo","body_mass: 4600<br />flipper_length: 218<br />species: gentoo<br />species: gentoo","body_mass: 5300<br />flipper_length: 218<br />species: gentoo<br />species: gentoo","body_mass: 4875<br />flipper_length: 212<br />species: gentoo<br />species: gentoo","body_mass: 5550<br />flipper_length: 230<br />species: gentoo<br />species: gentoo","body_mass: 4950<br />flipper_length: 218<br />species: gentoo<br />species: gentoo","body_mass: 5400<br />flipper_length: 228<br />species: gentoo<br />species: gentoo","body_mass: 4750<br />flipper_length: 212<br />species: gentoo<br />species: gentoo","body_mass: 5650<br />flipper_length: 224<br />species: gentoo<br />species: gentoo","body_mass: 4850<br />flipper_length: 214<br />species: gentoo<br />species: gentoo","body_mass: 5200<br />flipper_length: 226<br />species: gentoo<br />species: gentoo","body_mass: 4925<br />flipper_length: 216<br />species: gentoo<br />species: gentoo","body_mass: 4875<br />flipper_length: 222<br />species: gentoo<br />species: gentoo","body_mass: 4625<br />flipper_length: 203<br />species: gentoo<br />species: gentoo","body_mass: 5250<br />flipper_length: 225<br />species: gentoo<br />species: gentoo","body_mass: 4850<br />flipper_length: 219<br />species: gentoo<br />species: gentoo","body_mass: 5600<br />flipper_length: 228<br />species: gentoo<br />species: gentoo","body_mass: 4975<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 5500<br />flipper_length: 228<br />species: gentoo<br />species: gentoo","body_mass: 4725<br />flipper_length: 216<br />species: gentoo<br />species: gentoo","body_mass: 5500<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 4700<br />flipper_length: 210<br />species: gentoo<br />species: gentoo","body_mass: 5500<br />flipper_length: 219<br />species: gentoo<br />species: gentoo","body_mass: 4575<br />flipper_length: 208<br />species: gentoo<br />species: gentoo","body_mass: 5500<br />flipper_length: 209<br />species: gentoo<br />species: gentoo","body_mass: 5000<br />flipper_length: 216<br />species: gentoo<br />species: gentoo","body_mass: 5950<br />flipper_length: 229<br />species: gentoo<br />species: gentoo","body_mass: 4650<br />flipper_length: 213<br />species: gentoo<br />species: gentoo","body_mass: 5500<br />flipper_length: 230<br />species: gentoo<br />species: gentoo","body_mass: 4375<br />flipper_length: 217<br />species: gentoo<br />species: gentoo","body_mass: 5850<br />flipper_length: 230<br />species: gentoo<br />species: gentoo","body_mass: 4875<br />flipper_length: 217<br />species: gentoo<br />species: gentoo","body_mass: 6000<br />flipper_length: 222<br />species: gentoo<br />species: gentoo","body_mass: 4925<br />flipper_length: 214<br />species: gentoo<br />species: gentoo","body_mass:   NA<br />flipper_length:  NA<br />species: gentoo<br />species: gentoo","body_mass: 4850<br />flipper_length: 215<br />species: gentoo<br />species: gentoo","body_mass: 5750<br />flipper_length: 222<br />species: gentoo<br />species: gentoo","body_mass: 5200<br />flipper_length: 212<br />species: gentoo<br />species: gentoo","body_mass: 5400<br />flipper_length: 213<br />species: gentoo<br />species: gentoo"],"type":"scatter","mode":"markers","marker":{"autocolorscale":false,"color":"rgba(117,112,179,1)","opacity":1,"size":5.6692913385826778,"symbol":"square","line":{"width":1.8897637795275593,"color":"rgba(117,112,179,1)"}},"hoveron":"points","name":"gentoo","legendgroup":"gentoo","showlegend":true,"xaxis":"x","yaxis":"y","hoverinfo":"text","frame":null}],"layout":{"margin":{"t":43.762557077625573,"r":7.3059360730593621,"b":40.182648401826491,"l":43.105022831050235},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"title":{"text":"body mass versus flipper length by species","font":{"color":"rgba(0,0,0,1)","family":"","size":17.534246575342465},"x":0,"xref":"paper"},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[2520,6480],"tickmode":"array","ticktext":["3000","4000","5000","6000"],"tickvals":[3000,4000,5000,6000],"categoryorder":"array","categoryarray":["3000","4000","5000","6000"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"body mass (g)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[169.05000000000001,233.94999999999999],"tickmode":"array","ticktext":["170","180","190","200","210","220","230"],"tickvals":[170,180,190,200,210,220,230],"categoryorder":"array","categoryarray":["170","180","190","200","210","220","230"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"flipper length (mm)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":true,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498},"title":{"text":"species","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"c99463d35de0":{"x":{},"y":{},"colour":{},"shape":{},"type":"scatter"}},"cur_data":"c99463d35de0","visdat":{"c99463d35de0":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>In the next example, we make interactive parallel box plots of <code>bill_length</code> that distinguish between <code>species</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="co"># assign parallel box plot name</span></span>
<span id="cb82-2"><a href="#cb82-2" aria-hidden="true" tabindex="-1"></a>ggi2 <span class="ot">&lt;-</span> gg_penguin <span class="sc">+</span> <span class="fu">geom_boxplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> species, <span class="at">y =</span> bill_length))</span>
<span id="cb82-3"><a href="#cb82-3" aria-hidden="true" tabindex="-1"></a><span class="co"># make plot interactive</span></span>
<span id="cb82-4"><a href="#cb82-4" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplotly</span>(ggi2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="plotly html-widget html-fill-item" id="htmlwidget-ba17ce5d793b62ab57f0" style="width:100%;height:464px;"></div>
<script type="application/json" data-for="htmlwidget-ba17ce5d793b62ab57f0">{"x":{"data":[{"x":[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,3,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2],"y":[39.100000000000001,39.5,40.299999999999997,null,36.700000000000003,39.299999999999997,38.899999999999999,39.200000000000003,34.100000000000001,42,37.799999999999997,37.799999999999997,41.100000000000001,38.600000000000001,34.600000000000001,36.600000000000001,38.700000000000003,42.5,34.399999999999999,46,37.799999999999997,37.700000000000003,35.899999999999999,38.200000000000003,38.799999999999997,35.299999999999997,40.600000000000001,40.5,37.899999999999999,40.5,39.5,37.200000000000003,39.5,40.899999999999999,36.399999999999999,39.200000000000003,38.799999999999997,42.200000000000003,37.600000000000001,39.799999999999997,36.5,40.799999999999997,36,44.100000000000001,37,39.600000000000001,41.100000000000001,37.5,36,42.299999999999997,39.600000000000001,40.100000000000001,35,42,34.5,41.399999999999999,39,40.600000000000001,36.5,37.600000000000001,35.700000000000003,41.299999999999997,37.600000000000001,41.100000000000001,36.399999999999999,41.600000000000001,35.5,41.100000000000001,35.899999999999999,41.799999999999997,33.5,39.700000000000003,39.600000000000001,45.799999999999997,35.5,42.799999999999997,40.899999999999999,37.200000000000003,36.200000000000003,42.100000000000001,34.600000000000001,42.899999999999999,36.700000000000003,35.100000000000001,37.299999999999997,41.299999999999997,36.299999999999997,36.899999999999999,38.299999999999997,38.899999999999999,35.700000000000003,41.100000000000001,34,39.600000000000001,36.200000000000003,40.799999999999997,38.100000000000001,40.299999999999997,33.100000000000001,43.200000000000003,35,41,37.700000000000003,37.799999999999997,37.899999999999999,39.700000000000003,38.600000000000001,38.200000000000003,38.100000000000001,43.200000000000003,38.100000000000001,45.600000000000001,39.700000000000003,42.200000000000003,39.600000000000001,42.700000000000003,38.600000000000001,37.299999999999997,35.700000000000003,41.100000000000001,36.200000000000003,37.700000000000003,40.200000000000003,41.399999999999999,35.200000000000003,40.600000000000001,38.799999999999997,41.5,39,44.100000000000001,38.5,43.100000000000001,36.799999999999997,37.5,38.100000000000001,41.100000000000001,35.600000000000001,40.200000000000003,37,39.700000000000003,40.200000000000003,40.600000000000001,32.100000000000001,40.700000000000003,37.299999999999997,39,39.200000000000003,36.600000000000001,36,37.799999999999997,36,41.5,46.100000000000001,50,48.700000000000003,50,47.600000000000001,46.5,45.399999999999999,46.700000000000003,43.299999999999997,46.799999999999997,40.899999999999999,49,45.5,48.399999999999999,45.799999999999997,49.299999999999997,42,49.200000000000003,46.200000000000003,48.700000000000003,50.200000000000003,45.100000000000001,46.5,46.299999999999997,42.899999999999999,46.100000000000001,44.5,47.799999999999997,48.200000000000003,50,47.299999999999997,42.799999999999997,45.100000000000001,59.600000000000001,49.100000000000001,48.399999999999999,42.600000000000001,44.399999999999999,44,48.700000000000003,42.700000000000003,49.600000000000001,45.299999999999997,49.600000000000001,50.5,43.600000000000001,45.5,50.5,44.899999999999999,45.200000000000003,46.600000000000001,48.5,45.100000000000001,50.100000000000001,46.5,45,43.799999999999997,45.5,43.200000000000003,50.399999999999999,45.299999999999997,46.200000000000003,45.700000000000003,54.299999999999997,45.799999999999997,49.799999999999997,46.200000000000003,49.5,43.5,50.700000000000003,47.700000000000003,46.399999999999999,48.200000000000003,46.5,46.399999999999999,48.600000000000001,47.5,51.100000000000001,45.200000000000003,45.200000000000003,49.100000000000001,52.5,47.399999999999999,50,44.899999999999999,50.799999999999997,43.399999999999999,51.299999999999997,47.5,52.100000000000001,47.5,52.200000000000003,45.5,49.5,44.5,50.799999999999997,49.399999999999999,46.899999999999999,48.399999999999999,51.100000000000001,48.5,55.899999999999999,47.200000000000003,49.100000000000001,47.299999999999997,46.799999999999997,41.700000000000003,53.399999999999999,43.299999999999997,48.100000000000001,50.5,49.799999999999997,43.5,51.5,46.200000000000003,55.100000000000001,44.5,48.799999999999997,47.200000000000003,null,46.799999999999997,50.399999999999999,45.200000000000003,49.899999999999999,46.5,50,51.299999999999997,45.399999999999999,52.700000000000003,45.200000000000003,46.100000000000001,51.299999999999997,46,51.299999999999997,46.600000000000001,51.700000000000003,47,52,45.899999999999999,50.5,50.299999999999997,58,46.399999999999999,49.200000000000003,42.399999999999999,48.5,43.200000000000003,50.600000000000001,46.700000000000003,52,50.5,49.5,46.399999999999999,52.799999999999997,40.899999999999999,54.200000000000003,42.5,51,49.700000000000003,47.5,47.600000000000001,52,46.899999999999999,53.5,49,46.200000000000003,50.899999999999999,45.5,50.899999999999999,50.799999999999997,50.100000000000001,49,51.5,49.799999999999997,48.100000000000001,51.399999999999999,45.700000000000003,50.700000000000003,42.5,52.200000000000003,45.200000000000003,49.299999999999997,50.200000000000003,45.600000000000001,51.899999999999999,46.799999999999997,45.700000000000003,55.799999999999997,43.5,49.600000000000001,50.799999999999997,50.200000000000003],"hoverinfo":"y","type":"box","fillcolor":"rgba(255,255,255,1)","marker":{"opacity":null,"outliercolor":"rgba(0,0,0,1)","line":{"width":1.8897637795275593,"color":"rgba(0,0,0,1)"},"size":5.6692913385826778},"line":{"color":"rgba(51,51,51,1)","width":1.8897637795275593},"showlegend":false,"xaxis":"x","yaxis":"y","frame":null}],"layout":{"margin":{"t":26.228310502283104,"r":7.3059360730593621,"b":40.182648401826491,"l":37.260273972602747},"plot_bgcolor":"rgba(235,235,235,1)","paper_bgcolor":"rgba(255,255,255,1)","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724},"xaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[0.40000000000000002,3.6000000000000001],"tickmode":"array","ticktext":["adelie","chinstrap","gentoo"],"tickvals":[1,2,3],"categoryorder":"array","categoryarray":["adelie","chinstrap","gentoo"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"y","title":{"text":"species","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"yaxis":{"domain":[0,1],"automargin":true,"type":"linear","autorange":false,"range":[30.725000000000001,60.975000000000001],"tickmode":"array","ticktext":["40","50","60"],"tickvals":[40,50,60],"categoryorder":"array","categoryarray":["40","50","60"],"nticks":null,"ticks":"outside","tickcolor":"rgba(51,51,51,1)","ticklen":3.6529680365296811,"tickwidth":0.66417600664176002,"showticklabels":true,"tickfont":{"color":"rgba(77,77,77,1)","family":"","size":11.68949771689498},"tickangle":-0,"showline":false,"linecolor":null,"linewidth":0,"showgrid":true,"gridcolor":"rgba(255,255,255,1)","gridwidth":0.66417600664176002,"zeroline":false,"anchor":"x","title":{"text":"bill_length","font":{"color":"rgba(0,0,0,1)","family":"","size":14.611872146118724}},"hoverformat":".2f"},"shapes":[{"type":"rect","fillcolor":null,"line":{"color":null,"width":0,"linetype":[]},"yref":"paper","xref":"paper","x0":0,"x1":1,"y0":0,"y1":1}],"showlegend":false,"legend":{"bgcolor":"rgba(255,255,255,1)","bordercolor":"transparent","borderwidth":1.8897637795275593,"font":{"color":"rgba(0,0,0,1)","family":"","size":11.68949771689498}},"hovermode":"closest","barmode":"relative"},"config":{"doubleClick":"reset","modeBarButtonsToAdd":["hoverclosest","hovercompare"],"showSendToCloud":false},"source":"A","attrs":{"c994747b60e":{"x":{},"y":{},"type":"box"}},"cur_data":"c994747b60e","visdat":{"c994747b60e":["function (y) ","x"]},"highlight":{"on":"plotly_click","persistent":false,"dynamic":false,"selectize":false,"opacityDim":0.20000000000000001,"selected":{"opacity":1},"debounce":0},"shinyEvents":["plotly_hover","plotly_click","plotly_selected","plotly_relayout","plotly_brushed","plotly_brushing","plotly_clickannotation","plotly_doubleclick","plotly_deselect","plotly_afterplot","plotly_sunburstclick"],"base_url":"https://plot.ly"},"evals":[],"jsHooks":[]}</script>
</div>
</div>
<p>The interactive parallel box plot provides information about the box plot characteristics of each species (such as the minimum <code>bill_length</code>, Q1, median, Q3, etc.)</p>
</section>
</section>
</section>
<section id="a-plan-for-data-cleaning-and-exploration" class="level2" data-number="2.5">
<h2 data-number="2.5" class="anchored" data-anchor-id="a-plan-for-data-cleaning-and-exploration"><span class="header-section-number">2.5</span> A plan for data cleaning and exploration</h2>
<p>We have provided many examples of data cleaning and exploration using the <code>penguins_raw</code> data. The analysis above is NOT exhaustive, and there are many additional numeric and visual summaries we could consider. In what follows, we summarize a basic plan below for initial data cleaning and exploration that we have found useful. We assume that we are working with a data frame, which is the most common data structure used for data analysis in R.</p>
<ol type="1">
<li>Import or create the data set.</li>
<li>Use the <code>str</code> function to get an idea of the initial structure. This can help to identify clear issues we may have had in importing the data, problems with variable names and types, etc.</li>
<li>Clean the variable names based on our preferences.</li>
<li>Convert the variables to the appropriate type (e.g., categorical variables to <code>factor</code>).</li>
<li>Run the <code>summary</code> function on the data frame. Take note of <code>NAs</code>, impossible values that are data entry errors, etc. We may need to perform additional cleaning based on the information learned in this step.</li>
<li>Compute any additional numeric summaries of the different variables, as desired.</li>
<li>Create univariate plots of all variables being considered. Use histograms for discrete <code>numeric</code> variables, density plots for continuous <code>numeric</code> variables, and bar plots for <code>factor</code> variables. Take note of any interesting patterns such as modality, skewness, overall shape, outliers, etc.</li>
<li>Create bivariate plots for any pairs of variables. Use scatter plots for two <code>numeric</code> variables. Use parallel box plots for <code>numeric</code> and <code>factor</code> variables, or perhaps create histogram plots of the <code>numeric</code> variable facetted by the <code>factor</code> variable, or density plots of the <code>numeric</code> variables filled with different colors by the <code>factor</code> variable. Once again, notice any patterns.</li>
<li>Create multivariate and interactive graphics based on what we learn in the previous steps.</li>
</ol>
</section>
<section id="final-notes-on-missing-or-erroneous-data" class="level2" data-number="2.6">
<h2 data-number="2.6" class="anchored" data-anchor-id="final-notes-on-missing-or-erroneous-data"><span class="header-section-number">2.6</span> Final notes on missing or erroneous data</h2>
<p>What should we do with our data when observations are missing information or the information is clearly erroneous?</p>
<p>If the data are clearly erroneous, attempt to get the correct value. If the values cannot be corrected, replace them with <code>NA</code> since we don’t have that information.</p>
<p>What should we do about <code>NA</code>s? There are many approaches for dealing with <code>NA</code>s. The proper approach depends a lot on <em>why</em> the data are missing. Speaking informally, if there is no systematic reason causing the data to be missing, then ignoring the observations with missing data isn’t a terrible approach. However, if there is a systematic reason behind why the data are missing (such as individuals not wanting to answer a sensitive question, subjects dying for a specific reason, etc.) then ignoring that data can lead to erroneous conclusions.</p>
<p>In what follows, we will assume our missing data problem is not systematic and ignore missing values.</p>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list" style="display: none">
<div id="ref-brewer" class="csl-entry" role="listitem">
Brewer, Cynthia A. 2022. <span>“ColorBrewer2.org.”</span> <a href="https://colorbrewer2.org">https://colorbrewer2.org</a>.
</div>
<div id="ref-R-ggiraph" class="csl-entry" role="listitem">
Gohel, David, and Panagiotis Skintzos. 2024. <em>Ggiraph: Make Ggplot2 Graphics Interactive</em>. <a href="https://davidgohel.github.io/ggiraph/">https://davidgohel.github.io/ggiraph/</a>.
</div>
<div id="ref-GormanEtAl2014" class="csl-entry" role="listitem">
Gorman, Kristen B., Tony D. Williams, and William R. Fraser. 2014. <span>“Ecological Sexual Dimorphism and Environmental Variability Within a Community of Antarctic Penguins (Genus Pygoscelis).”</span> <em>PLOS ONE</em> 9 (3): 1–14. <a href="https://doi.org/10.1371/journal.pone.0090081">https://doi.org/10.1371/journal.pone.0090081</a>.
</div>
<div id="ref-R-palmerpenguins" class="csl-entry" role="listitem">
Horst, Allison, Alison Hill, and Kristen Gorman. 2022. <em>Palmerpenguins: Palmer Archipelago (Antarctica) Penguin Data</em>. <a href="https://allisonhorst.github.io/palmerpenguins/">https://allisonhorst.github.io/palmerpenguins/</a>.
</div>
<div id="ref-R-tibble" class="csl-entry" role="listitem">
Müller, Kirill, and Hadley Wickham. 2023. <em>Tibble: Simple Data Frames</em>. <a href="https://tibble.tidyverse.org/">https://tibble.tidyverse.org/</a>.
</div>
<div id="ref-plotly" class="csl-entry" role="listitem">
Plotly Technologies Inc. 2015. <span>“Collaborative Data Science.”</span> Montreal, QC: Plotly Technologies Inc. 2015. <a href="https://plot.ly">https://plot.ly</a>.
</div>
<div id="ref-R-plotly" class="csl-entry" role="listitem">
Sievert, Carson, Chris Parmer, Toby Hocking, Scott Chamberlain, Karthik Ram, Marianne Corvellec, and Pedro Despouy. 2024. <em>Plotly: Create Interactive Web Graphics via Plotly.js</em>. <a href="https://plotly-r.com">https://plotly-r.com</a>.
</div>
<div id="ref-tidyversestyleguide" class="csl-entry" role="listitem">
Wickham, Hadley. 2022. <em>The Tidyverse Style Guide</em>. <a href="https://style.tidyverse.org/">https://style.tidyverse.org/</a>.
</div>
<div id="ref-R-ggplot2" class="csl-entry" role="listitem">
Wickham, Hadley, Winston Chang, Lionel Henry, Thomas Lin Pedersen, Kohske Takahashi, Claus Wilke, Kara Woo, Hiroaki Yutani, Dewey Dunnington, and Teun van den Brand. 2024. <em>Ggplot2: Create Elegant Data Visualisations Using the Grammar of Graphics</em>. <a href="https://ggplot2.tidyverse.org">https://ggplot2.tidyverse.org</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./r-foundations.html" class="pagination-link" aria-label="R Foundations">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">R Foundations</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./parameter-estimation-and-model-fitting.html" class="pagination-link" aria-label="Parameter Estimation and Model Fitting">
        <span class="nav-page-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Parameter Estimation and Model Fitting</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->




</body></html>